var searchData=
[
  ['value_5fand_5fholder_0',['value_and_holder',['../structvalue__and__holder.html',1,'']]],
  ['valuecondition_1',['ValueCondition',['../struct_eigen_1_1_tensor_sycl_1_1internal_1_1_value_condition.html',1,'Eigen::TensorSycl::internal']]],
  ['valuecondition_3c_20false_2c_20x_2c_20y_20_3e_2',['ValueCondition&lt; false, X, Y &gt;',['../struct_eigen_1_1_tensor_sycl_1_1internal_1_1_value_condition_3_01false_00_01_x_00_01_y_01_4.html',1,'Eigen::TensorSycl::internal']]],
  ['values_5fand_5fholders_3',['values_and_holders',['../structvalues__and__holders.html',1,'']]],
  ['vanilla_4',['Vanilla',['../struct_vanilla.html',1,'']]],
  ['vanillastaticmix1_5',['VanillaStaticMix1',['../struct_vanilla_static_mix1.html',1,'']]],
  ['vanillastaticmix2_6',['VanillaStaticMix2',['../struct_vanilla_static_mix2.html',1,'']]],
  ['variable_5fif_5fdynamic_7',['variable_if_dynamic',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5frows_20_3e_8',['variable_if_dynamic&lt; Index, _Rows &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5fsubs_20_3e_9',['variable_if_dynamic&lt; Index, _Subs &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5fsupers_20_3e_10',['variable_if_dynamic&lt; Index, _Supers &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3acolsatcompiletime_20_3e_11',['variable_if_dynamic&lt; Index, ArgType::ColsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3arowsatcompiletime_20_3e_12',['variable_if_dynamic&lt; Index, ArgType::RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20colfactor_20_3e_13',['variable_if_dynamic&lt; Index, ColFactor &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20colsatcompiletime_20_3e_14',['variable_if_dynamic&lt; Index, ColsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20innerpanel_20_3f_20dynamic_20_3a0_20_3e_15',['variable_if_dynamic&lt; Index, InnerPanel ? Dynamic :0 &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20innerstrideatcompiletime_20_3e_16',['variable_if_dynamic&lt; Index, InnerStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20isvectoratcompiletime_20_3f_200_20_3aint_28isrowmajor_29_20_3f_20colsatcompiletime_20_3arowsatcompiletime_20_3e_17',['variable_if_dynamic&lt; Index, IsVectorAtCompileTime ? 0 :int(IsRowMajor) ? ColsAtCompileTime :RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20outersize_20_3e_18',['variable_if_dynamic&lt; Index, OuterSize &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20outerstrideatcompiletime_20_3e_19',['variable_if_dynamic&lt; Index, OuterStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20reversecol_20_3f_20argtype_3a_3acolsatcompiletime_20_3a1_20_3e_20',['variable_if_dynamic&lt; Index, ReverseCol ? ArgType::ColsAtCompileTime :1 &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20reverserow_20_3f_20argtype_3a_3arowsatcompiletime_20_3a1_20_3e_21',['variable_if_dynamic&lt; Index, ReverseRow ? ArgType::RowsAtCompileTime :1 &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rowfactor_20_3e_22',['variable_if_dynamic&lt; Index, RowFactor &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rows_20_3e_23',['variable_if_dynamic&lt; Index, Rows &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rowsatcompiletime_20_3e_24',['variable_if_dynamic&lt; Index, RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20subs_20_3e_25',['variable_if_dynamic&lt; Index, Subs &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20supers_20_3e_26',['variable_if_dynamic&lt; Index, Supers &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3acolsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_27',['variable_if_dynamic&lt; Index, XprType::ColsAtCompileTime==1 ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3ainnerstrideatcompiletime_20_3e_28',['variable_if_dynamic&lt; Index, XprType::InnerStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3aouterstrideatcompiletime_20_3e_29',['variable_if_dynamic&lt; Index, XprType::OuterStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3arowsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_30',['variable_if_dynamic&lt; Index, XprType::RowsAtCompileTime==1 ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_28argtype_3a_3acolsatcompiletime_3d_3d1_20_26_26blockcols_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_31',['variable_if_dynamic&lt; Index,(ArgType::ColsAtCompileTime==1 &amp;&amp;BlockCols==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_28argtype_3a_3arowsatcompiletime_3d_3d1_20_26_26blockrows_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_32',['variable_if_dynamic&lt; Index,(ArgType::RowsAtCompileTime==1 &amp;&amp;BlockRows==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20colsatcompiletime_20_3e_33',['variable_if_dynamic&lt; StorageIndex, ColsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20rowsatcompiletime_20_3e_34',['variable_if_dynamic&lt; StorageIndex, RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_28xprtype_3a_3acolsatcompiletime_3d_3d1_20_26_26blockcols_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_35',['variable_if_dynamic&lt; StorageIndex,(XprType::ColsAtCompileTime==1 &amp;&amp;BlockCols==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_28xprtype_3a_3arowsatcompiletime_3d_3d1_20_26_26blockrows_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_36',['variable_if_dynamic&lt; StorageIndex,(XprType::RowsAtCompileTime==1 &amp;&amp;BlockRows==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20t_2c_20dynamic_20_3e_37',['variable_if_dynamic&lt; T, Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic_3_01_t_00_01_dynamic_01_4.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_38',['variable_if_dynamicindex',['../class_eigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20index_2c_20diagindex_20_3e_39',['variable_if_dynamicindex&lt; Index, DiagIndex &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20index_2c_20xprtype_3a_3adiagindex_20_3e_40',['variable_if_dynamicindex&lt; Index, XprType::DiagIndex &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20t_2c_20dynamicindex_20_3e_41',['variable_if_dynamicindex&lt; T, DynamicIndex &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamicindex_3_01_t_00_01_dynamic_index_01_4.html',1,'Eigen::internal']]],
  ['variant_5fcaster_42',['variant_caster',['../structvariant__caster.html',1,'']]],
  ['variant_5fcaster_3c_20v_3c_20ts_2e_2e_2e_20_3e_20_3e_43',['variant_caster&lt; V&lt; Ts... &gt; &gt;',['../structvariant__caster_3_01_v_3_01_ts_8_8_8_01_4_01_4.html',1,'']]],
  ['variant_5fcaster_5fvisitor_44',['variant_caster_visitor',['../structvariant__caster__visitor.html',1,'']]],
  ['vec3_45',['Vec3',['../struct_vec3.html',1,'']]],
  ['vector2_46',['Vector2',['../class_vector2.html',1,'']]],
  ['vector_3c_20t_2c_20eigen_5faligned_5fallocator_3c_20t_20_3e_20_3e_47',['vector&lt; T, EIGEN_ALIGNED_ALLOCATOR&lt; T &gt; &gt;',['../classstd_1_1vector_3_01_t_00_01_e_i_g_e_n___a_l_i_g_n_e_d___a_l_l_o_c_a_t_o_r_3_01_t_01_4_01_4.html',1,'std']]],
  ['vector_5fhas_5fdata_5fand_5fformat_48',['vector_has_data_and_format',['../structvector__has__data__and__format.html',1,'']]],
  ['vector_5fhas_5fdata_5fand_5fformat_3c_20vector_2c_20enable_5fif_5ft_3c_20std_3a_3ais_5fsame_3c_20decltype_28format_5fdescriptor_3c_20typename_20vector_3a_3avalue_5ftype_20_3e_3a_3aformat_28_29_2c_20std_3a_3adeclval_3c_20vector_20_3e_28_29_2edata_28_29_29_2c_20typename_20vector_3a_3avalue_5ftype_20_2a_20_3e_3a_3avalue_20_3e_20_3e_49',['vector_has_data_and_format&lt; Vector, enable_if_t&lt; std::is_same&lt; decltype(format_descriptor&lt; typename Vector::value_type &gt;::format(), std::declval&lt; Vector &gt;().data()), typename Vector::value_type * &gt;::value &gt; &gt;',['../structvector__has__data__and__format_3_01_vector_00_01enable__if__t_3_01std_1_1is__same_3_01decl747d65b4a7fb391eecda178e3ef74ddd.html',1,'']]],
  ['vector_5fint_5fpair_50',['vector_int_pair',['../struct_eigen_1_1internal_1_1vector__int__pair.html',1,'Eigen::internal']]],
  ['vectorblock_51',['VectorBlock',['../class_eigen_1_1_vector_block.html',1,'Eigen']]],
  ['vectorization_5flogic_52',['vectorization_logic',['../structvectorization__logic.html',1,'']]],
  ['vectorization_5flogic_3c_20scalar_2c_20false_20_3e_53',['vectorization_logic&lt; Scalar, false &gt;',['../structvectorization__logic_3_01_scalar_00_01false_01_4.html',1,'']]],
  ['vectorization_5flogic_5fhalf_54',['vectorization_logic_half',['../structvectorization__logic__half.html',1,'']]],
  ['vectorization_5flogic_5fhalf_3c_20scalar_2c_20false_20_3e_55',['vectorization_logic_half&lt; Scalar, false &gt;',['../structvectorization__logic__half_3_01_scalar_00_01false_01_4.html',1,'']]],
  ['vectorize_5farg_56',['vectorize_arg',['../structvectorize__arg.html',1,'']]],
  ['vectorize_5fhelper_57',['vectorize_helper',['../structvectorize__helper.html',1,'']]],
  ['vectortype_58',['VectorType',['../struct_vector_type.html',1,'']]],
  ['vectortype_3c_20eigenvectorcontainer_2c_20scalar_20_3e_59',['VectorType&lt; EigenVectorContainer, Scalar &gt;',['../struct_vector_type_3_01_eigen_vector_container_00_01_scalar_01_4.html',1,'']]],
  ['vectortype_3c_20stdvectorcontainer_2c_20scalar_20_3e_60',['VectorType&lt; StdVectorContainer, Scalar &gt;',['../struct_vector_type_3_01_std_vector_container_00_01_scalar_01_4.html',1,'']]],
  ['vectorwise_5freverse_5finplace_5fimpl_61',['vectorwise_reverse_inplace_impl',['../struct_eigen_1_1internal_1_1vectorwise__reverse__inplace__impl.html',1,'Eigen::internal']]],
  ['vectorwise_5freverse_5finplace_5fimpl_3c_20horizontal_20_3e_62',['vectorwise_reverse_inplace_impl&lt; Horizontal &gt;',['../struct_eigen_1_1internal_1_1vectorwise__reverse__inplace__impl_3_01_horizontal_01_4.html',1,'Eigen::internal']]],
  ['vectorwise_5freverse_5finplace_5fimpl_3c_20vertical_20_3e_63',['vectorwise_reverse_inplace_impl&lt; Vertical &gt;',['../struct_eigen_1_1internal_1_1vectorwise__reverse__inplace__impl_3_01_vertical_01_4.html',1,'Eigen::internal']]],
  ['vectorwiseop_64',['VectorwiseOp',['../class_eigen_1_1_vectorwise_op.html',1,'Eigen']]],
  ['vertex_65',['Vertex',['../struct_vertex.html',1,'']]],
  ['vertex_5ft_66',['vertex_t',['../structvertex__t.html',1,'']]],
  ['visit_5fhelper_67',['visit_helper',['../structvisit__helper.html',1,'']]],
  ['visitor_5fevaluator_68',['visitor_evaluator',['../class_eigen_1_1internal_1_1visitor__evaluator.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_69',['visitor_impl',['../struct_eigen_1_1internal_1_1visitor__impl.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_3c_20visitor_2c_20derived_2c_201_20_3e_70',['visitor_impl&lt; Visitor, Derived, 1 &gt;',['../struct_eigen_1_1internal_1_1visitor__impl_3_01_visitor_00_01_derived_00_011_01_4.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_3c_20visitor_2c_20derived_2c_20dynamic_20_3e_71',['visitor_impl&lt; Visitor, Derived, Dynamic &gt;',['../struct_eigen_1_1internal_1_1visitor__impl_3_01_visitor_00_01_derived_00_01_dynamic_01_4.html',1,'Eigen::internal']]],
  ['vkacquirenextimageinfokhr_72',['VkAcquireNextImageInfoKHR',['../struct_vk_acquire_next_image_info_k_h_r.html',1,'']]],
  ['vkallocationcallbacks_73',['VkAllocationCallbacks',['../struct_vk_allocation_callbacks.html',1,'']]],
  ['vkapplicationinfo_74',['VkApplicationInfo',['../struct_vk_application_info.html',1,'']]],
  ['vkattachmentdescription_75',['VkAttachmentDescription',['../struct_vk_attachment_description.html',1,'']]],
  ['vkattachmentdescription2_76',['VkAttachmentDescription2',['../struct_vk_attachment_description2.html',1,'']]],
  ['vkattachmentdescriptionstencillayout_77',['VkAttachmentDescriptionStencilLayout',['../struct_vk_attachment_description_stencil_layout.html',1,'']]],
  ['vkattachmentreference_78',['VkAttachmentReference',['../struct_vk_attachment_reference.html',1,'']]],
  ['vkattachmentreference2_79',['VkAttachmentReference2',['../struct_vk_attachment_reference2.html',1,'']]],
  ['vkattachmentreferencestencillayout_80',['VkAttachmentReferenceStencilLayout',['../struct_vk_attachment_reference_stencil_layout.html',1,'']]],
  ['vkbaseinstructure_81',['VkBaseInStructure',['../struct_vk_base_in_structure.html',1,'']]],
  ['vkbaseoutstructure_82',['VkBaseOutStructure',['../struct_vk_base_out_structure.html',1,'']]],
  ['vkbindbuffermemorydevicegroupinfo_83',['VkBindBufferMemoryDeviceGroupInfo',['../struct_vk_bind_buffer_memory_device_group_info.html',1,'']]],
  ['vkbindbuffermemoryinfo_84',['VkBindBufferMemoryInfo',['../struct_vk_bind_buffer_memory_info.html',1,'']]],
  ['vkbindimagememorydevicegroupinfo_85',['VkBindImageMemoryDeviceGroupInfo',['../struct_vk_bind_image_memory_device_group_info.html',1,'']]],
  ['vkbindimagememoryinfo_86',['VkBindImageMemoryInfo',['../struct_vk_bind_image_memory_info.html',1,'']]],
  ['vkbindimagememoryswapchaininfokhr_87',['VkBindImageMemorySwapchainInfoKHR',['../struct_vk_bind_image_memory_swapchain_info_k_h_r.html',1,'']]],
  ['vkbindimageplanememoryinfo_88',['VkBindImagePlaneMemoryInfo',['../struct_vk_bind_image_plane_memory_info.html',1,'']]],
  ['vkbindsparseinfo_89',['VkBindSparseInfo',['../struct_vk_bind_sparse_info.html',1,'']]],
  ['vkblitimageinfo2_90',['VkBlitImageInfo2',['../struct_vk_blit_image_info2.html',1,'']]],
  ['vkbuffercopy_91',['VkBufferCopy',['../struct_vk_buffer_copy.html',1,'']]],
  ['vkbuffercopy2_92',['VkBufferCopy2',['../struct_vk_buffer_copy2.html',1,'']]],
  ['vkbuffercreateinfo_93',['VkBufferCreateInfo',['../struct_vk_buffer_create_info.html',1,'']]],
  ['vkbufferdeviceaddressinfo_94',['VkBufferDeviceAddressInfo',['../struct_vk_buffer_device_address_info.html',1,'']]],
  ['vkbufferimagecopy_95',['VkBufferImageCopy',['../struct_vk_buffer_image_copy.html',1,'']]],
  ['vkbufferimagecopy2_96',['VkBufferImageCopy2',['../struct_vk_buffer_image_copy2.html',1,'']]],
  ['vkbuffermemorybarrier_97',['VkBufferMemoryBarrier',['../struct_vk_buffer_memory_barrier.html',1,'']]],
  ['vkbuffermemorybarrier2_98',['VkBufferMemoryBarrier2',['../struct_vk_buffer_memory_barrier2.html',1,'']]],
  ['vkbuffermemoryrequirementsinfo2_99',['VkBufferMemoryRequirementsInfo2',['../struct_vk_buffer_memory_requirements_info2.html',1,'']]],
  ['vkbufferopaquecaptureaddresscreateinfo_100',['VkBufferOpaqueCaptureAddressCreateInfo',['../struct_vk_buffer_opaque_capture_address_create_info.html',1,'']]],
  ['vkbufferviewcreateinfo_101',['VkBufferViewCreateInfo',['../struct_vk_buffer_view_create_info.html',1,'']]],
  ['vkclearattachment_102',['VkClearAttachment',['../struct_vk_clear_attachment.html',1,'']]],
  ['vkclearcolorvalue_103',['VkClearColorValue',['../union_vk_clear_color_value.html',1,'']]],
  ['vkcleardepthstencilvalue_104',['VkClearDepthStencilValue',['../struct_vk_clear_depth_stencil_value.html',1,'']]],
  ['vkclearrect_105',['VkClearRect',['../struct_vk_clear_rect.html',1,'']]],
  ['vkclearvalue_106',['VkClearValue',['../union_vk_clear_value.html',1,'']]],
  ['vkcommandbufferallocateinfo_107',['VkCommandBufferAllocateInfo',['../struct_vk_command_buffer_allocate_info.html',1,'']]],
  ['vkcommandbufferbegininfo_108',['VkCommandBufferBeginInfo',['../struct_vk_command_buffer_begin_info.html',1,'']]],
  ['vkcommandbufferinheritanceinfo_109',['VkCommandBufferInheritanceInfo',['../struct_vk_command_buffer_inheritance_info.html',1,'']]],
  ['vkcommandbufferinheritancerenderinginfo_110',['VkCommandBufferInheritanceRenderingInfo',['../struct_vk_command_buffer_inheritance_rendering_info.html',1,'']]],
  ['vkcommandbuffersubmitinfo_111',['VkCommandBufferSubmitInfo',['../struct_vk_command_buffer_submit_info.html',1,'']]],
  ['vkcommandpoolcreateinfo_112',['VkCommandPoolCreateInfo',['../struct_vk_command_pool_create_info.html',1,'']]],
  ['vkcomponentmapping_113',['VkComponentMapping',['../struct_vk_component_mapping.html',1,'']]],
  ['vkcomputepipelinecreateinfo_114',['VkComputePipelineCreateInfo',['../struct_vk_compute_pipeline_create_info.html',1,'']]],
  ['vkconformanceversion_115',['VkConformanceVersion',['../struct_vk_conformance_version.html',1,'']]],
  ['vkcopybufferinfo2_116',['VkCopyBufferInfo2',['../struct_vk_copy_buffer_info2.html',1,'']]],
  ['vkcopybuffertoimageinfo2_117',['VkCopyBufferToImageInfo2',['../struct_vk_copy_buffer_to_image_info2.html',1,'']]],
  ['vkcopydescriptorset_118',['VkCopyDescriptorSet',['../struct_vk_copy_descriptor_set.html',1,'']]],
  ['vkcopyimageinfo2_119',['VkCopyImageInfo2',['../struct_vk_copy_image_info2.html',1,'']]],
  ['vkcopyimagetobufferinfo2_120',['VkCopyImageToBufferInfo2',['../struct_vk_copy_image_to_buffer_info2.html',1,'']]],
  ['vkdebugreportcallbackcreateinfoext_121',['VkDebugReportCallbackCreateInfoEXT',['../struct_vk_debug_report_callback_create_info_e_x_t.html',1,'']]],
  ['vkdependencyinfo_122',['VkDependencyInfo',['../struct_vk_dependency_info.html',1,'']]],
  ['vkdescriptorbufferinfo_123',['VkDescriptorBufferInfo',['../struct_vk_descriptor_buffer_info.html',1,'']]],
  ['vkdescriptorimageinfo_124',['VkDescriptorImageInfo',['../struct_vk_descriptor_image_info.html',1,'']]],
  ['vkdescriptorpoolcreateinfo_125',['VkDescriptorPoolCreateInfo',['../struct_vk_descriptor_pool_create_info.html',1,'']]],
  ['vkdescriptorpoolinlineuniformblockcreateinfo_126',['VkDescriptorPoolInlineUniformBlockCreateInfo',['../struct_vk_descriptor_pool_inline_uniform_block_create_info.html',1,'']]],
  ['vkdescriptorpoolsize_127',['VkDescriptorPoolSize',['../struct_vk_descriptor_pool_size.html',1,'']]],
  ['vkdescriptorsetallocateinfo_128',['VkDescriptorSetAllocateInfo',['../struct_vk_descriptor_set_allocate_info.html',1,'']]],
  ['vkdescriptorsetlayoutbinding_129',['VkDescriptorSetLayoutBinding',['../struct_vk_descriptor_set_layout_binding.html',1,'']]],
  ['vkdescriptorsetlayoutbindingflagscreateinfo_130',['VkDescriptorSetLayoutBindingFlagsCreateInfo',['../struct_vk_descriptor_set_layout_binding_flags_create_info.html',1,'']]],
  ['vkdescriptorsetlayoutcreateinfo_131',['VkDescriptorSetLayoutCreateInfo',['../struct_vk_descriptor_set_layout_create_info.html',1,'']]],
  ['vkdescriptorsetlayoutsupport_132',['VkDescriptorSetLayoutSupport',['../struct_vk_descriptor_set_layout_support.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountallocateinfo_133',['VkDescriptorSetVariableDescriptorCountAllocateInfo',['../struct_vk_descriptor_set_variable_descriptor_count_allocate_info.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountlayoutsupport_134',['VkDescriptorSetVariableDescriptorCountLayoutSupport',['../struct_vk_descriptor_set_variable_descriptor_count_layout_support.html',1,'']]],
  ['vkdescriptorupdatetemplatecreateinfo_135',['VkDescriptorUpdateTemplateCreateInfo',['../struct_vk_descriptor_update_template_create_info.html',1,'']]],
  ['vkdescriptorupdatetemplateentry_136',['VkDescriptorUpdateTemplateEntry',['../struct_vk_descriptor_update_template_entry.html',1,'']]],
  ['vkdevicebuffermemoryrequirements_137',['VkDeviceBufferMemoryRequirements',['../struct_vk_device_buffer_memory_requirements.html',1,'']]],
  ['vkdevicecreateinfo_138',['VkDeviceCreateInfo',['../struct_vk_device_create_info.html',1,'']]],
  ['vkdevicegroupbindsparseinfo_139',['VkDeviceGroupBindSparseInfo',['../struct_vk_device_group_bind_sparse_info.html',1,'']]],
  ['vkdevicegroupcommandbufferbegininfo_140',['VkDeviceGroupCommandBufferBeginInfo',['../struct_vk_device_group_command_buffer_begin_info.html',1,'']]],
  ['vkdevicegroupdevicecreateinfo_141',['VkDeviceGroupDeviceCreateInfo',['../struct_vk_device_group_device_create_info.html',1,'']]],
  ['vkdevicegrouppresentcapabilitieskhr_142',['VkDeviceGroupPresentCapabilitiesKHR',['../struct_vk_device_group_present_capabilities_k_h_r.html',1,'']]],
  ['vkdevicegrouppresentinfokhr_143',['VkDeviceGroupPresentInfoKHR',['../struct_vk_device_group_present_info_k_h_r.html',1,'']]],
  ['vkdevicegrouprenderpassbegininfo_144',['VkDeviceGroupRenderPassBeginInfo',['../struct_vk_device_group_render_pass_begin_info.html',1,'']]],
  ['vkdevicegroupsubmitinfo_145',['VkDeviceGroupSubmitInfo',['../struct_vk_device_group_submit_info.html',1,'']]],
  ['vkdevicegroupswapchaincreateinfokhr_146',['VkDeviceGroupSwapchainCreateInfoKHR',['../struct_vk_device_group_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkdeviceimagememoryrequirements_147',['VkDeviceImageMemoryRequirements',['../struct_vk_device_image_memory_requirements.html',1,'']]],
  ['vkdevicememoryopaquecaptureaddressinfo_148',['VkDeviceMemoryOpaqueCaptureAddressInfo',['../struct_vk_device_memory_opaque_capture_address_info.html',1,'']]],
  ['vkdeviceprivatedatacreateinfo_149',['VkDevicePrivateDataCreateInfo',['../struct_vk_device_private_data_create_info.html',1,'']]],
  ['vkdevicequeuecreateinfo_150',['VkDeviceQueueCreateInfo',['../struct_vk_device_queue_create_info.html',1,'']]],
  ['vkdevicequeueinfo2_151',['VkDeviceQueueInfo2',['../struct_vk_device_queue_info2.html',1,'']]],
  ['vkdispatchindirectcommand_152',['VkDispatchIndirectCommand',['../struct_vk_dispatch_indirect_command.html',1,'']]],
  ['vkdisplaymodecreateinfokhr_153',['VkDisplayModeCreateInfoKHR',['../struct_vk_display_mode_create_info_k_h_r.html',1,'']]],
  ['vkdisplaymodeparameterskhr_154',['VkDisplayModeParametersKHR',['../struct_vk_display_mode_parameters_k_h_r.html',1,'']]],
  ['vkdisplaymodepropertieskhr_155',['VkDisplayModePropertiesKHR',['../struct_vk_display_mode_properties_k_h_r.html',1,'']]],
  ['vkdisplayplanecapabilitieskhr_156',['VkDisplayPlaneCapabilitiesKHR',['../struct_vk_display_plane_capabilities_k_h_r.html',1,'']]],
  ['vkdisplayplanepropertieskhr_157',['VkDisplayPlanePropertiesKHR',['../struct_vk_display_plane_properties_k_h_r.html',1,'']]],
  ['vkdisplaypresentinfokhr_158',['VkDisplayPresentInfoKHR',['../struct_vk_display_present_info_k_h_r.html',1,'']]],
  ['vkdisplaypropertieskhr_159',['VkDisplayPropertiesKHR',['../struct_vk_display_properties_k_h_r.html',1,'']]],
  ['vkdisplaysurfacecreateinfokhr_160',['VkDisplaySurfaceCreateInfoKHR',['../struct_vk_display_surface_create_info_k_h_r.html',1,'']]],
  ['vkdrawindexedindirectcommand_161',['VkDrawIndexedIndirectCommand',['../struct_vk_draw_indexed_indirect_command.html',1,'']]],
  ['vkdrawindirectcommand_162',['VkDrawIndirectCommand',['../struct_vk_draw_indirect_command.html',1,'']]],
  ['vkeventcreateinfo_163',['VkEventCreateInfo',['../struct_vk_event_create_info.html',1,'']]],
  ['vkexportfencecreateinfo_164',['VkExportFenceCreateInfo',['../struct_vk_export_fence_create_info.html',1,'']]],
  ['vkexportmemoryallocateinfo_165',['VkExportMemoryAllocateInfo',['../struct_vk_export_memory_allocate_info.html',1,'']]],
  ['vkexportsemaphorecreateinfo_166',['VkExportSemaphoreCreateInfo',['../struct_vk_export_semaphore_create_info.html',1,'']]],
  ['vkextensionproperties_167',['VkExtensionProperties',['../struct_vk_extension_properties.html',1,'']]],
  ['vkextent2d_168',['VkExtent2D',['../struct_vk_extent2_d.html',1,'']]],
  ['vkextent3d_169',['VkExtent3D',['../struct_vk_extent3_d.html',1,'']]],
  ['vkexternalbufferproperties_170',['VkExternalBufferProperties',['../struct_vk_external_buffer_properties.html',1,'']]],
  ['vkexternalfenceproperties_171',['VkExternalFenceProperties',['../struct_vk_external_fence_properties.html',1,'']]],
  ['vkexternalimageformatproperties_172',['VkExternalImageFormatProperties',['../struct_vk_external_image_format_properties.html',1,'']]],
  ['vkexternalmemorybuffercreateinfo_173',['VkExternalMemoryBufferCreateInfo',['../struct_vk_external_memory_buffer_create_info.html',1,'']]],
  ['vkexternalmemoryimagecreateinfo_174',['VkExternalMemoryImageCreateInfo',['../struct_vk_external_memory_image_create_info.html',1,'']]],
  ['vkexternalmemoryproperties_175',['VkExternalMemoryProperties',['../struct_vk_external_memory_properties.html',1,'']]],
  ['vkexternalsemaphoreproperties_176',['VkExternalSemaphoreProperties',['../struct_vk_external_semaphore_properties.html',1,'']]],
  ['vkfencecreateinfo_177',['VkFenceCreateInfo',['../struct_vk_fence_create_info.html',1,'']]],
  ['vkformatproperties_178',['VkFormatProperties',['../struct_vk_format_properties.html',1,'']]],
  ['vkformatproperties2_179',['VkFormatProperties2',['../struct_vk_format_properties2.html',1,'']]],
  ['vkformatproperties3_180',['VkFormatProperties3',['../struct_vk_format_properties3.html',1,'']]],
  ['vkframebufferattachmentimageinfo_181',['VkFramebufferAttachmentImageInfo',['../struct_vk_framebuffer_attachment_image_info.html',1,'']]],
  ['vkframebufferattachmentscreateinfo_182',['VkFramebufferAttachmentsCreateInfo',['../struct_vk_framebuffer_attachments_create_info.html',1,'']]],
  ['vkframebuffercreateinfo_183',['VkFramebufferCreateInfo',['../struct_vk_framebuffer_create_info.html',1,'']]],
  ['vkgraphicspipelinecreateinfo_184',['VkGraphicsPipelineCreateInfo',['../struct_vk_graphics_pipeline_create_info.html',1,'']]],
  ['vkimageblit_185',['VkImageBlit',['../struct_vk_image_blit.html',1,'']]],
  ['vkimageblit2_186',['VkImageBlit2',['../struct_vk_image_blit2.html',1,'']]],
  ['vkimagecopy_187',['VkImageCopy',['../struct_vk_image_copy.html',1,'']]],
  ['vkimagecopy2_188',['VkImageCopy2',['../struct_vk_image_copy2.html',1,'']]],
  ['vkimagecreateinfo_189',['VkImageCreateInfo',['../struct_vk_image_create_info.html',1,'']]],
  ['vkimageformatlistcreateinfo_190',['VkImageFormatListCreateInfo',['../struct_vk_image_format_list_create_info.html',1,'']]],
  ['vkimageformatproperties_191',['VkImageFormatProperties',['../struct_vk_image_format_properties.html',1,'']]],
  ['vkimageformatproperties2_192',['VkImageFormatProperties2',['../struct_vk_image_format_properties2.html',1,'']]],
  ['vkimagememorybarrier_193',['VkImageMemoryBarrier',['../struct_vk_image_memory_barrier.html',1,'']]],
  ['vkimagememorybarrier2_194',['VkImageMemoryBarrier2',['../struct_vk_image_memory_barrier2.html',1,'']]],
  ['vkimagememoryrequirementsinfo2_195',['VkImageMemoryRequirementsInfo2',['../struct_vk_image_memory_requirements_info2.html',1,'']]],
  ['vkimageplanememoryrequirementsinfo_196',['VkImagePlaneMemoryRequirementsInfo',['../struct_vk_image_plane_memory_requirements_info.html',1,'']]],
  ['vkimageresolve_197',['VkImageResolve',['../struct_vk_image_resolve.html',1,'']]],
  ['vkimageresolve2_198',['VkImageResolve2',['../struct_vk_image_resolve2.html',1,'']]],
  ['vkimagesparsememoryrequirementsinfo2_199',['VkImageSparseMemoryRequirementsInfo2',['../struct_vk_image_sparse_memory_requirements_info2.html',1,'']]],
  ['vkimagestencilusagecreateinfo_200',['VkImageStencilUsageCreateInfo',['../struct_vk_image_stencil_usage_create_info.html',1,'']]],
  ['vkimagesubresource_201',['VkImageSubresource',['../struct_vk_image_subresource.html',1,'']]],
  ['vkimagesubresourcelayers_202',['VkImageSubresourceLayers',['../struct_vk_image_subresource_layers.html',1,'']]],
  ['vkimagesubresourcerange_203',['VkImageSubresourceRange',['../struct_vk_image_subresource_range.html',1,'']]],
  ['vkimageswapchaincreateinfokhr_204',['VkImageSwapchainCreateInfoKHR',['../struct_vk_image_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkimageviewcreateinfo_205',['VkImageViewCreateInfo',['../struct_vk_image_view_create_info.html',1,'']]],
  ['vkimageviewusagecreateinfo_206',['VkImageViewUsageCreateInfo',['../struct_vk_image_view_usage_create_info.html',1,'']]],
  ['vkinputattachmentaspectreference_207',['VkInputAttachmentAspectReference',['../struct_vk_input_attachment_aspect_reference.html',1,'']]],
  ['vkinstancecreateinfo_208',['VkInstanceCreateInfo',['../struct_vk_instance_create_info.html',1,'']]],
  ['vklayerproperties_209',['VkLayerProperties',['../struct_vk_layer_properties.html',1,'']]],
  ['vkmacossurfacecreateinfomvk_210',['VkMacOSSurfaceCreateInfoMVK',['../struct_vk_mac_o_s_surface_create_info_m_v_k.html',1,'']]],
  ['vkmappedmemoryrange_211',['VkMappedMemoryRange',['../struct_vk_mapped_memory_range.html',1,'']]],
  ['vkmemoryallocateflagsinfo_212',['VkMemoryAllocateFlagsInfo',['../struct_vk_memory_allocate_flags_info.html',1,'']]],
  ['vkmemoryallocateinfo_213',['VkMemoryAllocateInfo',['../struct_vk_memory_allocate_info.html',1,'']]],
  ['vkmemorybarrier_214',['VkMemoryBarrier',['../struct_vk_memory_barrier.html',1,'']]],
  ['vkmemorybarrier2_215',['VkMemoryBarrier2',['../struct_vk_memory_barrier2.html',1,'']]],
  ['vkmemorydedicatedallocateinfo_216',['VkMemoryDedicatedAllocateInfo',['../struct_vk_memory_dedicated_allocate_info.html',1,'']]],
  ['vkmemorydedicatedrequirements_217',['VkMemoryDedicatedRequirements',['../struct_vk_memory_dedicated_requirements.html',1,'']]],
  ['vkmemoryheap_218',['VkMemoryHeap',['../struct_vk_memory_heap.html',1,'']]],
  ['vkmemoryopaquecaptureaddressallocateinfo_219',['VkMemoryOpaqueCaptureAddressAllocateInfo',['../struct_vk_memory_opaque_capture_address_allocate_info.html',1,'']]],
  ['vkmemoryrequirements_220',['VkMemoryRequirements',['../struct_vk_memory_requirements.html',1,'']]],
  ['vkmemoryrequirements2_221',['VkMemoryRequirements2',['../struct_vk_memory_requirements2.html',1,'']]],
  ['vkmemorytype_222',['VkMemoryType',['../struct_vk_memory_type.html',1,'']]],
  ['vkmetalsurfacecreateinfoext_223',['VkMetalSurfaceCreateInfoEXT',['../struct_vk_metal_surface_create_info_e_x_t.html',1,'']]],
  ['vkmirsurfacecreateinfokhr_224',['VkMirSurfaceCreateInfoKHR',['../struct_vk_mir_surface_create_info_k_h_r.html',1,'']]],
  ['vkoffset2d_225',['VkOffset2D',['../struct_vk_offset2_d.html',1,'']]],
  ['vkoffset3d_226',['VkOffset3D',['../struct_vk_offset3_d.html',1,'']]],
  ['vkphysicaldevice16bitstoragefeatures_227',['VkPhysicalDevice16BitStorageFeatures',['../struct_vk_physical_device16_bit_storage_features.html',1,'']]],
  ['vkphysicaldevice8bitstoragefeatures_228',['VkPhysicalDevice8BitStorageFeatures',['../struct_vk_physical_device8_bit_storage_features.html',1,'']]],
  ['vkphysicaldevicebufferdeviceaddressfeatures_229',['VkPhysicalDeviceBufferDeviceAddressFeatures',['../struct_vk_physical_device_buffer_device_address_features.html',1,'']]],
  ['vkphysicaldevicedepthstencilresolveproperties_230',['VkPhysicalDeviceDepthStencilResolveProperties',['../struct_vk_physical_device_depth_stencil_resolve_properties.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingfeatures_231',['VkPhysicalDeviceDescriptorIndexingFeatures',['../struct_vk_physical_device_descriptor_indexing_features.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingproperties_232',['VkPhysicalDeviceDescriptorIndexingProperties',['../struct_vk_physical_device_descriptor_indexing_properties.html',1,'']]],
  ['vkphysicaldevicedriverproperties_233',['VkPhysicalDeviceDriverProperties',['../struct_vk_physical_device_driver_properties.html',1,'']]],
  ['vkphysicaldevicedynamicrenderingfeatures_234',['VkPhysicalDeviceDynamicRenderingFeatures',['../struct_vk_physical_device_dynamic_rendering_features.html',1,'']]],
  ['vkphysicaldeviceexternalbufferinfo_235',['VkPhysicalDeviceExternalBufferInfo',['../struct_vk_physical_device_external_buffer_info.html',1,'']]],
  ['vkphysicaldeviceexternalfenceinfo_236',['VkPhysicalDeviceExternalFenceInfo',['../struct_vk_physical_device_external_fence_info.html',1,'']]],
  ['vkphysicaldeviceexternalimageformatinfo_237',['VkPhysicalDeviceExternalImageFormatInfo',['../struct_vk_physical_device_external_image_format_info.html',1,'']]],
  ['vkphysicaldeviceexternalsemaphoreinfo_238',['VkPhysicalDeviceExternalSemaphoreInfo',['../struct_vk_physical_device_external_semaphore_info.html',1,'']]],
  ['vkphysicaldevicefeatures_239',['VkPhysicalDeviceFeatures',['../struct_vk_physical_device_features.html',1,'']]],
  ['vkphysicaldevicefeatures2_240',['VkPhysicalDeviceFeatures2',['../struct_vk_physical_device_features2.html',1,'']]],
  ['vkphysicaldevicefloatcontrolsproperties_241',['VkPhysicalDeviceFloatControlsProperties',['../struct_vk_physical_device_float_controls_properties.html',1,'']]],
  ['vkphysicaldevicegroupproperties_242',['VkPhysicalDeviceGroupProperties',['../struct_vk_physical_device_group_properties.html',1,'']]],
  ['vkphysicaldevicehostqueryresetfeatures_243',['VkPhysicalDeviceHostQueryResetFeatures',['../struct_vk_physical_device_host_query_reset_features.html',1,'']]],
  ['vkphysicaldeviceidproperties_244',['VkPhysicalDeviceIDProperties',['../struct_vk_physical_device_i_d_properties.html',1,'']]],
  ['vkphysicaldeviceimageformatinfo2_245',['VkPhysicalDeviceImageFormatInfo2',['../struct_vk_physical_device_image_format_info2.html',1,'']]],
  ['vkphysicaldeviceimagelessframebufferfeatures_246',['VkPhysicalDeviceImagelessFramebufferFeatures',['../struct_vk_physical_device_imageless_framebuffer_features.html',1,'']]],
  ['vkphysicaldeviceimagerobustnessfeatures_247',['VkPhysicalDeviceImageRobustnessFeatures',['../struct_vk_physical_device_image_robustness_features.html',1,'']]],
  ['vkphysicaldeviceinlineuniformblockfeatures_248',['VkPhysicalDeviceInlineUniformBlockFeatures',['../struct_vk_physical_device_inline_uniform_block_features.html',1,'']]],
  ['vkphysicaldeviceinlineuniformblockproperties_249',['VkPhysicalDeviceInlineUniformBlockProperties',['../struct_vk_physical_device_inline_uniform_block_properties.html',1,'']]],
  ['vkphysicaldevicelimits_250',['VkPhysicalDeviceLimits',['../struct_vk_physical_device_limits.html',1,'']]],
  ['vkphysicaldevicemaintenance3properties_251',['VkPhysicalDeviceMaintenance3Properties',['../struct_vk_physical_device_maintenance3_properties.html',1,'']]],
  ['vkphysicaldevicemaintenance4features_252',['VkPhysicalDeviceMaintenance4Features',['../struct_vk_physical_device_maintenance4_features.html',1,'']]],
  ['vkphysicaldevicemaintenance4properties_253',['VkPhysicalDeviceMaintenance4Properties',['../struct_vk_physical_device_maintenance4_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties_254',['VkPhysicalDeviceMemoryProperties',['../struct_vk_physical_device_memory_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties2_255',['VkPhysicalDeviceMemoryProperties2',['../struct_vk_physical_device_memory_properties2.html',1,'']]],
  ['vkphysicaldevicemultiviewfeatures_256',['VkPhysicalDeviceMultiviewFeatures',['../struct_vk_physical_device_multiview_features.html',1,'']]],
  ['vkphysicaldevicemultiviewproperties_257',['VkPhysicalDeviceMultiviewProperties',['../struct_vk_physical_device_multiview_properties.html',1,'']]],
  ['vkphysicaldevicepipelinecreationcachecontrolfeatures_258',['VkPhysicalDevicePipelineCreationCacheControlFeatures',['../struct_vk_physical_device_pipeline_creation_cache_control_features.html',1,'']]],
  ['vkphysicaldevicepointclippingproperties_259',['VkPhysicalDevicePointClippingProperties',['../struct_vk_physical_device_point_clipping_properties.html',1,'']]],
  ['vkphysicaldeviceprivatedatafeatures_260',['VkPhysicalDevicePrivateDataFeatures',['../struct_vk_physical_device_private_data_features.html',1,'']]],
  ['vkphysicaldeviceproperties_261',['VkPhysicalDeviceProperties',['../struct_vk_physical_device_properties.html',1,'']]],
  ['vkphysicaldeviceproperties2_262',['VkPhysicalDeviceProperties2',['../struct_vk_physical_device_properties2.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryfeatures_263',['VkPhysicalDeviceProtectedMemoryFeatures',['../struct_vk_physical_device_protected_memory_features.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryproperties_264',['VkPhysicalDeviceProtectedMemoryProperties',['../struct_vk_physical_device_protected_memory_properties.html',1,'']]],
  ['vkphysicaldevicesamplerfilterminmaxproperties_265',['VkPhysicalDeviceSamplerFilterMinmaxProperties',['../struct_vk_physical_device_sampler_filter_minmax_properties.html',1,'']]],
  ['vkphysicaldevicesamplerycbcrconversionfeatures_266',['VkPhysicalDeviceSamplerYcbcrConversionFeatures',['../struct_vk_physical_device_sampler_ycbcr_conversion_features.html',1,'']]],
  ['vkphysicaldevicescalarblocklayoutfeatures_267',['VkPhysicalDeviceScalarBlockLayoutFeatures',['../struct_vk_physical_device_scalar_block_layout_features.html',1,'']]],
  ['vkphysicaldeviceseparatedepthstencillayoutsfeatures_268',['VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures',['../struct_vk_physical_device_separate_depth_stencil_layouts_features.html',1,'']]],
  ['vkphysicaldeviceshaderatomicint64features_269',['VkPhysicalDeviceShaderAtomicInt64Features',['../struct_vk_physical_device_shader_atomic_int64_features.html',1,'']]],
  ['vkphysicaldeviceshaderdemotetohelperinvocationfeatures_270',['VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures',['../struct_vk_physical_device_shader_demote_to_helper_invocation_features.html',1,'']]],
  ['vkphysicaldeviceshaderdrawparametersfeatures_271',['VkPhysicalDeviceShaderDrawParametersFeatures',['../struct_vk_physical_device_shader_draw_parameters_features.html',1,'']]],
  ['vkphysicaldeviceshaderfloat16int8features_272',['VkPhysicalDeviceShaderFloat16Int8Features',['../struct_vk_physical_device_shader_float16_int8_features.html',1,'']]],
  ['vkphysicaldeviceshaderintegerdotproductfeatures_273',['VkPhysicalDeviceShaderIntegerDotProductFeatures',['../struct_vk_physical_device_shader_integer_dot_product_features.html',1,'']]],
  ['vkphysicaldeviceshaderintegerdotproductproperties_274',['VkPhysicalDeviceShaderIntegerDotProductProperties',['../struct_vk_physical_device_shader_integer_dot_product_properties.html',1,'']]],
  ['vkphysicaldeviceshadersubgroupextendedtypesfeatures_275',['VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures',['../struct_vk_physical_device_shader_subgroup_extended_types_features.html',1,'']]],
  ['vkphysicaldeviceshaderterminateinvocationfeatures_276',['VkPhysicalDeviceShaderTerminateInvocationFeatures',['../struct_vk_physical_device_shader_terminate_invocation_features.html',1,'']]],
  ['vkphysicaldevicesparseimageformatinfo2_277',['VkPhysicalDeviceSparseImageFormatInfo2',['../struct_vk_physical_device_sparse_image_format_info2.html',1,'']]],
  ['vkphysicaldevicesparseproperties_278',['VkPhysicalDeviceSparseProperties',['../struct_vk_physical_device_sparse_properties.html',1,'']]],
  ['vkphysicaldevicesubgroupproperties_279',['VkPhysicalDeviceSubgroupProperties',['../struct_vk_physical_device_subgroup_properties.html',1,'']]],
  ['vkphysicaldevicesubgroupsizecontrolfeatures_280',['VkPhysicalDeviceSubgroupSizeControlFeatures',['../struct_vk_physical_device_subgroup_size_control_features.html',1,'']]],
  ['vkphysicaldevicesubgroupsizecontrolproperties_281',['VkPhysicalDeviceSubgroupSizeControlProperties',['../struct_vk_physical_device_subgroup_size_control_properties.html',1,'']]],
  ['vkphysicaldevicesynchronization2features_282',['VkPhysicalDeviceSynchronization2Features',['../struct_vk_physical_device_synchronization2_features.html',1,'']]],
  ['vkphysicaldevicetexelbufferalignmentproperties_283',['VkPhysicalDeviceTexelBufferAlignmentProperties',['../struct_vk_physical_device_texel_buffer_alignment_properties.html',1,'']]],
  ['vkphysicaldevicetexturecompressionastchdrfeatures_284',['VkPhysicalDeviceTextureCompressionASTCHDRFeatures',['../struct_vk_physical_device_texture_compression_a_s_t_c_h_d_r_features.html',1,'']]],
  ['vkphysicaldevicetimelinesemaphorefeatures_285',['VkPhysicalDeviceTimelineSemaphoreFeatures',['../struct_vk_physical_device_timeline_semaphore_features.html',1,'']]],
  ['vkphysicaldevicetimelinesemaphoreproperties_286',['VkPhysicalDeviceTimelineSemaphoreProperties',['../struct_vk_physical_device_timeline_semaphore_properties.html',1,'']]],
  ['vkphysicaldevicetoolproperties_287',['VkPhysicalDeviceToolProperties',['../struct_vk_physical_device_tool_properties.html',1,'']]],
  ['vkphysicaldeviceuniformbufferstandardlayoutfeatures_288',['VkPhysicalDeviceUniformBufferStandardLayoutFeatures',['../struct_vk_physical_device_uniform_buffer_standard_layout_features.html',1,'']]],
  ['vkphysicaldevicevariablepointersfeatures_289',['VkPhysicalDeviceVariablePointersFeatures',['../struct_vk_physical_device_variable_pointers_features.html',1,'']]],
  ['vkphysicaldevicevulkan11features_290',['VkPhysicalDeviceVulkan11Features',['../struct_vk_physical_device_vulkan11_features.html',1,'']]],
  ['vkphysicaldevicevulkan11properties_291',['VkPhysicalDeviceVulkan11Properties',['../struct_vk_physical_device_vulkan11_properties.html',1,'']]],
  ['vkphysicaldevicevulkan12features_292',['VkPhysicalDeviceVulkan12Features',['../struct_vk_physical_device_vulkan12_features.html',1,'']]],
  ['vkphysicaldevicevulkan12properties_293',['VkPhysicalDeviceVulkan12Properties',['../struct_vk_physical_device_vulkan12_properties.html',1,'']]],
  ['vkphysicaldevicevulkan13features_294',['VkPhysicalDeviceVulkan13Features',['../struct_vk_physical_device_vulkan13_features.html',1,'']]],
  ['vkphysicaldevicevulkan13properties_295',['VkPhysicalDeviceVulkan13Properties',['../struct_vk_physical_device_vulkan13_properties.html',1,'']]],
  ['vkphysicaldevicevulkanmemorymodelfeatures_296',['VkPhysicalDeviceVulkanMemoryModelFeatures',['../struct_vk_physical_device_vulkan_memory_model_features.html',1,'']]],
  ['vkphysicaldevicezeroinitializeworkgroupmemoryfeatures_297',['VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures',['../struct_vk_physical_device_zero_initialize_workgroup_memory_features.html',1,'']]],
  ['vkpipelinecachecreateinfo_298',['VkPipelineCacheCreateInfo',['../struct_vk_pipeline_cache_create_info.html',1,'']]],
  ['vkpipelinecacheheaderversionone_299',['VkPipelineCacheHeaderVersionOne',['../struct_vk_pipeline_cache_header_version_one.html',1,'']]],
  ['vkpipelinecolorblendattachmentstate_300',['VkPipelineColorBlendAttachmentState',['../struct_vk_pipeline_color_blend_attachment_state.html',1,'']]],
  ['vkpipelinecolorblendstatecreateinfo_301',['VkPipelineColorBlendStateCreateInfo',['../struct_vk_pipeline_color_blend_state_create_info.html',1,'']]],
  ['vkpipelinecreationfeedback_302',['VkPipelineCreationFeedback',['../struct_vk_pipeline_creation_feedback.html',1,'']]],
  ['vkpipelinecreationfeedbackcreateinfo_303',['VkPipelineCreationFeedbackCreateInfo',['../struct_vk_pipeline_creation_feedback_create_info.html',1,'']]],
  ['vkpipelinedepthstencilstatecreateinfo_304',['VkPipelineDepthStencilStateCreateInfo',['../struct_vk_pipeline_depth_stencil_state_create_info.html',1,'']]],
  ['vkpipelinedynamicstatecreateinfo_305',['VkPipelineDynamicStateCreateInfo',['../struct_vk_pipeline_dynamic_state_create_info.html',1,'']]],
  ['vkpipelineinputassemblystatecreateinfo_306',['VkPipelineInputAssemblyStateCreateInfo',['../struct_vk_pipeline_input_assembly_state_create_info.html',1,'']]],
  ['vkpipelinelayoutcreateinfo_307',['VkPipelineLayoutCreateInfo',['../struct_vk_pipeline_layout_create_info.html',1,'']]],
  ['vkpipelinemultisamplestatecreateinfo_308',['VkPipelineMultisampleStateCreateInfo',['../struct_vk_pipeline_multisample_state_create_info.html',1,'']]],
  ['vkpipelinerasterizationstatecreateinfo_309',['VkPipelineRasterizationStateCreateInfo',['../struct_vk_pipeline_rasterization_state_create_info.html',1,'']]],
  ['vkpipelinerenderingcreateinfo_310',['VkPipelineRenderingCreateInfo',['../struct_vk_pipeline_rendering_create_info.html',1,'']]],
  ['vkpipelineshaderstagecreateinfo_311',['VkPipelineShaderStageCreateInfo',['../struct_vk_pipeline_shader_stage_create_info.html',1,'']]],
  ['vkpipelineshaderstagerequiredsubgroupsizecreateinfo_312',['VkPipelineShaderStageRequiredSubgroupSizeCreateInfo',['../struct_vk_pipeline_shader_stage_required_subgroup_size_create_info.html',1,'']]],
  ['vkpipelinetessellationdomainoriginstatecreateinfo_313',['VkPipelineTessellationDomainOriginStateCreateInfo',['../struct_vk_pipeline_tessellation_domain_origin_state_create_info.html',1,'']]],
  ['vkpipelinetessellationstatecreateinfo_314',['VkPipelineTessellationStateCreateInfo',['../struct_vk_pipeline_tessellation_state_create_info.html',1,'']]],
  ['vkpipelinevertexinputstatecreateinfo_315',['VkPipelineVertexInputStateCreateInfo',['../struct_vk_pipeline_vertex_input_state_create_info.html',1,'']]],
  ['vkpipelineviewportstatecreateinfo_316',['VkPipelineViewportStateCreateInfo',['../struct_vk_pipeline_viewport_state_create_info.html',1,'']]],
  ['vkpresentinfokhr_317',['VkPresentInfoKHR',['../struct_vk_present_info_k_h_r.html',1,'']]],
  ['vkprivatedataslotcreateinfo_318',['VkPrivateDataSlotCreateInfo',['../struct_vk_private_data_slot_create_info.html',1,'']]],
  ['vkprotectedsubmitinfo_319',['VkProtectedSubmitInfo',['../struct_vk_protected_submit_info.html',1,'']]],
  ['vkpushconstantrange_320',['VkPushConstantRange',['../struct_vk_push_constant_range.html',1,'']]],
  ['vkquerypoolcreateinfo_321',['VkQueryPoolCreateInfo',['../struct_vk_query_pool_create_info.html',1,'']]],
  ['vkqueuefamilyproperties_322',['VkQueueFamilyProperties',['../struct_vk_queue_family_properties.html',1,'']]],
  ['vkqueuefamilyproperties2_323',['VkQueueFamilyProperties2',['../struct_vk_queue_family_properties2.html',1,'']]],
  ['vkrect2d_324',['VkRect2D',['../struct_vk_rect2_d.html',1,'']]],
  ['vkrenderingattachmentinfo_325',['VkRenderingAttachmentInfo',['../struct_vk_rendering_attachment_info.html',1,'']]],
  ['vkrenderinginfo_326',['VkRenderingInfo',['../struct_vk_rendering_info.html',1,'']]],
  ['vkrenderpassattachmentbegininfo_327',['VkRenderPassAttachmentBeginInfo',['../struct_vk_render_pass_attachment_begin_info.html',1,'']]],
  ['vkrenderpassbegininfo_328',['VkRenderPassBeginInfo',['../struct_vk_render_pass_begin_info.html',1,'']]],
  ['vkrenderpasscreateinfo_329',['VkRenderPassCreateInfo',['../struct_vk_render_pass_create_info.html',1,'']]],
  ['vkrenderpasscreateinfo2_330',['VkRenderPassCreateInfo2',['../struct_vk_render_pass_create_info2.html',1,'']]],
  ['vkrenderpassinputattachmentaspectcreateinfo_331',['VkRenderPassInputAttachmentAspectCreateInfo',['../struct_vk_render_pass_input_attachment_aspect_create_info.html',1,'']]],
  ['vkrenderpassmultiviewcreateinfo_332',['VkRenderPassMultiviewCreateInfo',['../struct_vk_render_pass_multiview_create_info.html',1,'']]],
  ['vkresolveimageinfo2_333',['VkResolveImageInfo2',['../struct_vk_resolve_image_info2.html',1,'']]],
  ['vksamplercreateinfo_334',['VkSamplerCreateInfo',['../struct_vk_sampler_create_info.html',1,'']]],
  ['vksamplerreductionmodecreateinfo_335',['VkSamplerReductionModeCreateInfo',['../struct_vk_sampler_reduction_mode_create_info.html',1,'']]],
  ['vksamplerycbcrconversioncreateinfo_336',['VkSamplerYcbcrConversionCreateInfo',['../struct_vk_sampler_ycbcr_conversion_create_info.html',1,'']]],
  ['vksamplerycbcrconversionimageformatproperties_337',['VkSamplerYcbcrConversionImageFormatProperties',['../struct_vk_sampler_ycbcr_conversion_image_format_properties.html',1,'']]],
  ['vksamplerycbcrconversioninfo_338',['VkSamplerYcbcrConversionInfo',['../struct_vk_sampler_ycbcr_conversion_info.html',1,'']]],
  ['vksemaphorecreateinfo_339',['VkSemaphoreCreateInfo',['../struct_vk_semaphore_create_info.html',1,'']]],
  ['vksemaphoresignalinfo_340',['VkSemaphoreSignalInfo',['../struct_vk_semaphore_signal_info.html',1,'']]],
  ['vksemaphoresubmitinfo_341',['VkSemaphoreSubmitInfo',['../struct_vk_semaphore_submit_info.html',1,'']]],
  ['vksemaphoretypecreateinfo_342',['VkSemaphoreTypeCreateInfo',['../struct_vk_semaphore_type_create_info.html',1,'']]],
  ['vksemaphorewaitinfo_343',['VkSemaphoreWaitInfo',['../struct_vk_semaphore_wait_info.html',1,'']]],
  ['vkshadermodulecreateinfo_344',['VkShaderModuleCreateInfo',['../struct_vk_shader_module_create_info.html',1,'']]],
  ['vksparsebuffermemorybindinfo_345',['VkSparseBufferMemoryBindInfo',['../struct_vk_sparse_buffer_memory_bind_info.html',1,'']]],
  ['vksparseimageformatproperties_346',['VkSparseImageFormatProperties',['../struct_vk_sparse_image_format_properties.html',1,'']]],
  ['vksparseimageformatproperties2_347',['VkSparseImageFormatProperties2',['../struct_vk_sparse_image_format_properties2.html',1,'']]],
  ['vksparseimagememorybind_348',['VkSparseImageMemoryBind',['../struct_vk_sparse_image_memory_bind.html',1,'']]],
  ['vksparseimagememorybindinfo_349',['VkSparseImageMemoryBindInfo',['../struct_vk_sparse_image_memory_bind_info.html',1,'']]],
  ['vksparseimagememoryrequirements_350',['VkSparseImageMemoryRequirements',['../struct_vk_sparse_image_memory_requirements.html',1,'']]],
  ['vksparseimagememoryrequirements2_351',['VkSparseImageMemoryRequirements2',['../struct_vk_sparse_image_memory_requirements2.html',1,'']]],
  ['vksparseimageopaquememorybindinfo_352',['VkSparseImageOpaqueMemoryBindInfo',['../struct_vk_sparse_image_opaque_memory_bind_info.html',1,'']]],
  ['vksparsememorybind_353',['VkSparseMemoryBind',['../struct_vk_sparse_memory_bind.html',1,'']]],
  ['vkspecializationinfo_354',['VkSpecializationInfo',['../struct_vk_specialization_info.html',1,'']]],
  ['vkspecializationmapentry_355',['VkSpecializationMapEntry',['../struct_vk_specialization_map_entry.html',1,'']]],
  ['vkstencilopstate_356',['VkStencilOpState',['../struct_vk_stencil_op_state.html',1,'']]],
  ['vksubmitinfo_357',['VkSubmitInfo',['../struct_vk_submit_info.html',1,'']]],
  ['vksubmitinfo2_358',['VkSubmitInfo2',['../struct_vk_submit_info2.html',1,'']]],
  ['vksubpassbegininfo_359',['VkSubpassBeginInfo',['../struct_vk_subpass_begin_info.html',1,'']]],
  ['vksubpassdependency_360',['VkSubpassDependency',['../struct_vk_subpass_dependency.html',1,'']]],
  ['vksubpassdependency2_361',['VkSubpassDependency2',['../struct_vk_subpass_dependency2.html',1,'']]],
  ['vksubpassdescription_362',['VkSubpassDescription',['../struct_vk_subpass_description.html',1,'']]],
  ['vksubpassdescription2_363',['VkSubpassDescription2',['../struct_vk_subpass_description2.html',1,'']]],
  ['vksubpassdescriptiondepthstencilresolve_364',['VkSubpassDescriptionDepthStencilResolve',['../struct_vk_subpass_description_depth_stencil_resolve.html',1,'']]],
  ['vksubpassendinfo_365',['VkSubpassEndInfo',['../struct_vk_subpass_end_info.html',1,'']]],
  ['vksubresourcelayout_366',['VkSubresourceLayout',['../struct_vk_subresource_layout.html',1,'']]],
  ['vksurfacecapabilitieskhr_367',['VkSurfaceCapabilitiesKHR',['../struct_vk_surface_capabilities_k_h_r.html',1,'']]],
  ['vksurfaceformatkhr_368',['VkSurfaceFormatKHR',['../struct_vk_surface_format_k_h_r.html',1,'']]],
  ['vkswapchaincreateinfokhr_369',['VkSwapchainCreateInfoKHR',['../struct_vk_swapchain_create_info_k_h_r.html',1,'']]],
  ['vktimelinesemaphoresubmitinfo_370',['VkTimelineSemaphoreSubmitInfo',['../struct_vk_timeline_semaphore_submit_info.html',1,'']]],
  ['vkvertexinputattributedescription_371',['VkVertexInputAttributeDescription',['../struct_vk_vertex_input_attribute_description.html',1,'']]],
  ['vkvertexinputbindingdescription_372',['VkVertexInputBindingDescription',['../struct_vk_vertex_input_binding_description.html',1,'']]],
  ['vkviewport_373',['VkViewport',['../struct_vk_viewport.html',1,'']]],
  ['vkwaylandsurfacecreateinfokhr_374',['VkWaylandSurfaceCreateInfoKHR',['../struct_vk_wayland_surface_create_info_k_h_r.html',1,'']]],
  ['vkwin32surfacecreateinfokhr_375',['VkWin32SurfaceCreateInfoKHR',['../struct_vk_win32_surface_create_info_k_h_r.html',1,'']]],
  ['vkwritedescriptorset_376',['VkWriteDescriptorSet',['../struct_vk_write_descriptor_set.html',1,'']]],
  ['vkwritedescriptorsetinlineuniformblock_377',['VkWriteDescriptorSetInlineUniformBlock',['../struct_vk_write_descriptor_set_inline_uniform_block.html',1,'']]],
  ['vkxcbsurfacecreateinfokhr_378',['VkXcbSurfaceCreateInfoKHR',['../struct_vk_xcb_surface_create_info_k_h_r.html',1,'']]],
  ['vkxlibsurfacecreateinfokhr_379',['VkXlibSurfaceCreateInfoKHR',['../struct_vk_xlib_surface_create_info_k_h_r.html',1,'']]],
  ['vml_5fassign_5ftraits_380',['vml_assign_traits',['../class_eigen_1_1internal_1_1vml__assign__traits.html',1,'Eigen::internal']]],
  ['voicestate_381',['VoiceState',['../class_voice_state.html',1,'']]],
  ['void_5fcaster_382',['void_caster',['../structvoid__caster.html',1,'']]],
  ['void_5fcaster_3c_20std_3a_3anullptr_5ft_20_3e_383',['void_caster&lt; std::nullptr_t &gt;',['../structvoid__caster.html',1,'']]],
  ['void_5fcaster_3c_20void_5ftype_20_3e_384',['void_caster&lt; void_type &gt;',['../structvoid__caster.html',1,'']]],
  ['void_5ft_5fimpl_385',['void_t_impl',['../structvoid__t__impl.html',1,'']]],
  ['void_5ftype_386',['void_type',['../structvoid__type.html',1,'']]],
  ['vscrollpanel_387',['VScrollPanel',['../class_v_scroll_panel.html',1,'']]]
];
