var searchData=
[
  ['val_20tt_0',['val tt',['../eigen_tensors.html#autotoc_md154',1,'&lt;tt&gt;&lt;Operation&gt; constant(const Scalar&amp; val)&lt;/tt&gt;'],['../eigen_tensors.html#autotoc_md147',1,'&lt;tt&gt;&lt;Tensor-Type&gt; setConstant(const Scalar&amp; val)&lt;/tt&gt;']]],
  ['validity_20of_20operations_1',['Validity of operations',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialMatrixArithmetic.dox#TutorialArithmeticValidity',1,'']]],
  ['value_2',['value',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/UnalignedArrayAssert.dox#c3',1,'Cause 3: Passing Eigen objects by value'],['../class_eigen_1_1_dense_base.html#a8da735a6bfc7012606acf787156d10a0',1,'Eigen::DenseBase::value()'],['../class_eigen_1_1_triplet.html#ab11e2110141dc8f144992b0693e00580',1,'Eigen::Triplet::value()'],['../classenum__.html#adc91736df0da3714b34ef9f991d3e7ed',1,'enum_::value()'],['../structargument__record.html#a3d6ba6a0cb59834720cb7d7df5bdb2c2',1,'argument_record::value'],['../class_form_widget_3_01_t_00_01typename_01std_1_1is__enum_3_01_t_01_4_1_1type_01_4.html#a99f8765e38c5dde9572cfb029ab7e932',1,'FormWidget&lt; T, typename std::is_enum&lt; T &gt;::type &gt;::value()'],['../class_form_widget_3_01_color_00_01std_1_1true__type_01_4.html#afcd3421150c1df180789f5cc050ea9a7',1,'FormWidget&lt; Color, std::true_type &gt;::value()'],['../class_eigen_1_1_inner_iterator.html#ab04bccb41eb22ffcb92dc61125aab119',1,'Eigen::InnerIterator::value()'],['../class_form_widget_3_01bool_00_01std_1_1true__type_01_4.html#a5f0700c6282aa0f34a45f3f8c616fae6',1,'FormWidget&lt; bool, std::true_type &gt;::value()'],['../class_eigen_1_1_bench_timer.html#a26760f963ed8b64c126159bfea57735e',1,'Eigen::BenchTimer::value()'],['../structarg__v.html#a3fe738ed6397b48b88244151dab53ee1',1,'arg_v::value']]],
  ['value_20dynamic_3',['The special value Dynamic',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialMatrixClass.dox#TutorialMatrixDynamic',1,'']]],
  ['value_5fand_5fholder_4',['value_and_holder',['../structvalue__and__holder.html',1,'']]],
  ['value_5ftype_5',['value_type',['../class_eigen_1_1_sparse_matrix_base.html#ac254d3b61718ebc2136d27bac043dcb7',1,'Eigen::SparseMatrixBase::value_type'],['../class_eigen_1_1_dense_base.html#a9276182dab8236c33f1e7abf491d504d',1,'Eigen::DenseBase::value_type']]],
  ['valuecondition_6',['ValueCondition',['../struct_eigen_1_1_tensor_sycl_1_1internal_1_1_value_condition.html',1,'Eigen::TensorSycl::internal']]],
  ['valuecondition_3c_20false_2c_20x_2c_20y_20_3e_7',['ValueCondition&lt; false, X, Y &gt;',['../struct_eigen_1_1_tensor_sycl_1_1internal_1_1_value_condition_3_01false_00_01_x_00_01_y_01_4.html',1,'Eigen::TensorSycl::internal']]],
  ['valueptr_8',['valueptr',['../class_eigen_1_1_sparse_map_base_3_01_derived_00_01_read_only_accessors_01_4.html#a159381ba25ecf67a23d9b0b78de1235b',1,'Eigen::SparseMapBase&lt; Derived, ReadOnlyAccessors &gt;::valuePtr()'],['../class_eigen_1_1_sparse_compressed_base.html#a6373c1dab09c6d3db8fe5e4eea060a86',1,'Eigen::SparseCompressedBase::valuePtr() const'],['../class_eigen_1_1_sparse_compressed_base.html#aa99f79283d649526977b6058caead4cc',1,'Eigen::SparseCompressedBase::valuePtr()'],['../class_eigen_1_1_sparse_map_base_3_01_derived_00_01_write_accessors_01_4.html#a2f496a35ee9ac16a1fb2d1269fff2a22',1,'Eigen::SparseMapBase&lt; Derived, WriteAccessors &gt;::valuePtr()'],['../class_eigen_1_1_sparse_matrix.html#ab5f971ff967ee031ab8941b76c5af940',1,'Eigen::SparseMatrix::valuePtr() const'],['../class_eigen_1_1_sparse_matrix.html#a42e4af8a3773be123d2e35fba266627e',1,'Eigen::SparseMatrix::valuePtr()'],['../class_eigen_1_1_sparse_map_base_3_01_derived_00_01_write_accessors_01_4.html#a159381ba25ecf67a23d9b0b78de1235b',1,'Eigen::SparseMapBase&lt; Derived, WriteAccessors &gt;::valuePtr()'],['../class_eigen_1_1internal_1_1_mapped_super_nodal_matrix.html#acedbbc0412bd6041c9dae2d1a66c1649',1,'Eigen::internal::MappedSuperNodalMatrix::valuePtr()']]],
  ['values_9',['values',['../eigen_tensors.html#autotoc_md218',1,'Representation of scalar values'],['../intro_guide.html#init_hints_values',1,'Supported and default values'],['../window_guide.html#window_hints_values',1,'Supported and default values']]],
  ['values_20but_20the_20api_20wants_20me_20to_20divide_20one_20by_20the_20other_20and_20put_20the_20result_20in_20a_20floating_20point_20number_20won_20t_20this_20case_20problems_20for_20long_20running_20conversions_10',['Q7 : I have input and output sample rates that are integer values, but the API wants me to divide one by the other and put the result in a floating point number. Won&apos;t this case problems for long running conversions?',['..//Users/ferluht/Dev/rpidaw/3rdparty/libsamplerate/docs/faq.md#Q007',1,'']]],
  ['values_20inside_20an_20array_11',['Accessing values inside an Array',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialArrayClass.dox#TutorialArrayClassAccess',1,'']]],
  ['values_5fand_5fholders_12',['values_and_holders',['../structvalues__and__holders.html',1,'']]],
  ['vanilla_13',['Vanilla',['../struct_vanilla.html',1,'']]],
  ['vanillastaticmix1_14',['VanillaStaticMix1',['../struct_vanilla_static_mix1.html',1,'']]],
  ['vanillastaticmix2_15',['VanillaStaticMix2',['../struct_vanilla_static_mix2.html',1,'']]],
  ['variable_5fif_5fdynamic_16',['variable_if_dynamic',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5frows_20_3e_17',['variable_if_dynamic&lt; Index, _Rows &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5fsubs_20_3e_18',['variable_if_dynamic&lt; Index, _Subs &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20_5fsupers_20_3e_19',['variable_if_dynamic&lt; Index, _Supers &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3acolsatcompiletime_20_3e_20',['variable_if_dynamic&lt; Index, ArgType::ColsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20argtype_3a_3arowsatcompiletime_20_3e_21',['variable_if_dynamic&lt; Index, ArgType::RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20colfactor_20_3e_22',['variable_if_dynamic&lt; Index, ColFactor &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20colsatcompiletime_20_3e_23',['variable_if_dynamic&lt; Index, ColsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20innerpanel_20_3f_20dynamic_20_3a0_20_3e_24',['variable_if_dynamic&lt; Index, InnerPanel ? Dynamic :0 &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20innerstrideatcompiletime_20_3e_25',['variable_if_dynamic&lt; Index, InnerStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20isvectoratcompiletime_20_3f_200_20_3aint_28isrowmajor_29_20_3f_20colsatcompiletime_20_3arowsatcompiletime_20_3e_26',['variable_if_dynamic&lt; Index, IsVectorAtCompileTime ? 0 :int(IsRowMajor) ? ColsAtCompileTime :RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20outersize_20_3e_27',['variable_if_dynamic&lt; Index, OuterSize &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20outerstrideatcompiletime_20_3e_28',['variable_if_dynamic&lt; Index, OuterStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20reversecol_20_3f_20argtype_3a_3acolsatcompiletime_20_3a1_20_3e_29',['variable_if_dynamic&lt; Index, ReverseCol ? ArgType::ColsAtCompileTime :1 &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20reverserow_20_3f_20argtype_3a_3arowsatcompiletime_20_3a1_20_3e_30',['variable_if_dynamic&lt; Index, ReverseRow ? ArgType::RowsAtCompileTime :1 &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rowfactor_20_3e_31',['variable_if_dynamic&lt; Index, RowFactor &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rows_20_3e_32',['variable_if_dynamic&lt; Index, Rows &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20rowsatcompiletime_20_3e_33',['variable_if_dynamic&lt; Index, RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20subs_20_3e_34',['variable_if_dynamic&lt; Index, Subs &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20supers_20_3e_35',['variable_if_dynamic&lt; Index, Supers &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3acolsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_36',['variable_if_dynamic&lt; Index, XprType::ColsAtCompileTime==1 ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3ainnerstrideatcompiletime_20_3e_37',['variable_if_dynamic&lt; Index, XprType::InnerStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3aouterstrideatcompiletime_20_3e_38',['variable_if_dynamic&lt; Index, XprType::OuterStrideAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_20xprtype_3a_3arowsatcompiletime_3d_3d1_20_3f_200_20_3adynamic_20_3e_39',['variable_if_dynamic&lt; Index, XprType::RowsAtCompileTime==1 ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_28argtype_3a_3acolsatcompiletime_3d_3d1_20_26_26blockcols_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_40',['variable_if_dynamic&lt; Index,(ArgType::ColsAtCompileTime==1 &amp;&amp;BlockCols==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20index_2c_28argtype_3a_3arowsatcompiletime_3d_3d1_20_26_26blockrows_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_41',['variable_if_dynamic&lt; Index,(ArgType::RowsAtCompileTime==1 &amp;&amp;BlockRows==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20colsatcompiletime_20_3e_42',['variable_if_dynamic&lt; StorageIndex, ColsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_20rowsatcompiletime_20_3e_43',['variable_if_dynamic&lt; StorageIndex, RowsAtCompileTime &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_28xprtype_3a_3acolsatcompiletime_3d_3d1_20_26_26blockcols_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_44',['variable_if_dynamic&lt; StorageIndex,(XprType::ColsAtCompileTime==1 &amp;&amp;BlockCols==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20storageindex_2c_28xprtype_3a_3arowsatcompiletime_3d_3d1_20_26_26blockrows_3d_3d1_29_20_3f_200_20_3adynamic_20_3e_45',['variable_if_dynamic&lt; StorageIndex,(XprType::RowsAtCompileTime==1 &amp;&amp;BlockRows==1) ? 0 :Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamic_3c_20t_2c_20dynamic_20_3e_46',['variable_if_dynamic&lt; T, Dynamic &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamic_3_01_t_00_01_dynamic_01_4.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_47',['variable_if_dynamicindex',['../class_eigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20index_2c_20diagindex_20_3e_48',['variable_if_dynamicindex&lt; Index, DiagIndex &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20index_2c_20xprtype_3a_3adiagindex_20_3e_49',['variable_if_dynamicindex&lt; Index, XprType::DiagIndex &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamicindex.html',1,'Eigen::internal']]],
  ['variable_5fif_5fdynamicindex_3c_20t_2c_20dynamicindex_20_3e_50',['variable_if_dynamicindex&lt; T, DynamicIndex &gt;',['../class_eigen_1_1internal_1_1variable__if__dynamicindex_3_01_t_00_01_dynamic_index_01_4.html',1,'Eigen::internal']]],
  ['variables_51',['variables',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialMapClass.dox#TutorialMapTypes',1,'Map types and declaring Map variables'],['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialMapClass.dox#TutorialMapUsing',1,'Using Map variables']]],
  ['variant_5fcaster_52',['variant_caster',['../structvariant__caster.html',1,'']]],
  ['variant_5fcaster_3c_20v_3c_20ts_2e_2e_2e_20_3e_20_3e_53',['variant_caster&lt; V&lt; Ts... &gt; &gt;',['../structvariant__caster_3_01_v_3_01_ts_8_8_8_01_4_01_4.html',1,'']]],
  ['variant_5fcaster_5fvisitor_54',['variant_caster_visitor',['../structvariant__caster__visitor.html',1,'']]],
  ['vec_55',['vec',['../class_eigen_1_1_quaternion_base.html#ae7927333472826cc8c471ebb9984dd89',1,'Eigen::QuaternionBase::vec() const'],['../class_eigen_1_1_quaternion_base.html#a3464bef51c839f557a1e75c80d8ef167',1,'Eigen::QuaternionBase::vec()']]],
  ['vec3_56',['Vec3',['../struct_vec3.html',1,'']]],
  ['vector_20blocks_57',['Vector blocks',['../_eigen2_to_eigen3.html#VectorBlocks',1,'']]],
  ['vector_20multiplication_58',['Matrix-matrix and matrix-vector multiplication',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialMatrixArithmetic.dox#TutorialArithmeticMatrixMul',1,'']]],
  ['vector_20types_59',['Array, matrix and vector types',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/QuickReference.dox#QuickRef_Types',1,'']]],
  ['vector2_60',['Vector2',['../class_vector2.html',1,'']]],
  ['vector2f_61',['Vector2f',['../nanogui_2include_2nanogui_2common_8h.html#aeaa91c7416823e7ec36091276df1117a',1,'common.h']]],
  ['vector2i_62',['Vector2i',['../nanogui_2include_2nanogui_2common_8h.html#a4d8870d979b7f5bbae7e642d3df096db',1,'common.h']]],
  ['vector3_63',['vector3',['../class_eigen_1_1_quaternion_base.html#a974c0529d55983b0b3a6d99a8466f331',1,'Eigen::QuaternionBase::Vector3'],['../class_eigen_1_1_euler_angles.html#af0f446aa0f46b3439abedff63fabf39c',1,'Eigen::EulerAngles::Vector3']]],
  ['vector3f_64',['Vector3f',['../nanogui_2include_2nanogui_2common_8h.html#a28a50d6df2d99beaa9f68f926cb8f4ca',1,'common.h']]],
  ['vector3i_65',['Vector3i',['../nanogui_2include_2nanogui_2common_8h.html#a1c45ab85f57da94b7fb79a3e2e9cc526',1,'common.h']]],
  ['vector4f_66',['Vector4f',['../nanogui_2include_2nanogui_2common_8h.html#ad240893c7a5a4a831bcaaa5976f7bcb4',1,'common.h']]],
  ['vector4i_67',['Vector4i',['../nanogui_2include_2nanogui_2common_8h.html#a61fb5ef83e426799e2cd244f782e82b1',1,'common.h']]],
  ['vector_3c_20t_2c_20eigen_5faligned_5fallocator_3c_20t_20_3e_20_3e_68',['vector&lt; T, EIGEN_ALIGNED_ALLOCATOR&lt; T &gt; &gt;',['../classstd_1_1vector_3_01_t_00_01_e_i_g_e_n___a_l_i_g_n_e_d___a_l_l_o_c_a_t_o_r_3_01_t_01_4_01_4.html',1,'std']]],
  ['vector_5fhas_5fdata_5fand_5fformat_69',['vector_has_data_and_format',['../structvector__has__data__and__format.html',1,'']]],
  ['vector_5fhas_5fdata_5fand_5fformat_3c_20vector_2c_20enable_5fif_5ft_3c_20std_3a_3ais_5fsame_3c_20decltype_28format_5fdescriptor_3c_20typename_20vector_3a_3avalue_5ftype_20_3e_3a_3aformat_28_29_2c_20std_3a_3adeclval_3c_20vector_20_3e_28_29_2edata_28_29_29_2c_20typename_20vector_3a_3avalue_5ftype_20_2a_20_3e_3a_3avalue_20_3e_20_3e_70',['vector_has_data_and_format&lt; Vector, enable_if_t&lt; std::is_same&lt; decltype(format_descriptor&lt; typename Vector::value_type &gt;::format(), std::declval&lt; Vector &gt;().data()), typename Vector::value_type * &gt;::value &gt; &gt;',['../structvector__has__data__and__format_3_01_vector_00_01enable__if__t_3_01std_1_1is__same_3_01decl747d65b4a7fb391eecda178e3ef74ddd.html',1,'']]],
  ['vector_5fint_5fpair_71',['vector_int_pair',['../struct_eigen_1_1internal_1_1vector__int__pair.html',1,'Eigen::internal']]],
  ['vectorblock_72',['vectorblock',['../class_eigen_1_1_vector_block.html#a4bd5eb61b2c420218269a111d717dbb7',1,'Eigen::VectorBlock::VectorBlock(VectorType &amp;vector, Index start, Index size)'],['../class_eigen_1_1_vector_block.html#a94bcec1eda40d989b2fbcc70f343fa8f',1,'Eigen::VectorBlock::VectorBlock(VectorType &amp;vector, Index start)'],['../class_eigen_1_1_vector_block.html',1,'Eigen::VectorBlock&lt; VectorType, Size &gt;']]],
  ['vectord_73',['vectord',['../class_eigen_1_1_l_d_l_t.html#aaddd3a9ecb0b429578d377d7a48826d8',1,'Eigen::LDLT::vectorD()'],['../class_eigen_1_1_simplicial_l_d_l_t.html#abe54532ce80558a0474b11763702107b',1,'Eigen::SimplicialLDLT::vectorD()']]],
  ['vectorization_74',['Vectorization',['../_topic_vectorization.html',1,'UnclassifiedPages']]],
  ['vectorization_20and_20performance_20tweaking_75',['Alignment, vectorization and performance tweaking',['../_topic_preprocessor_directives.html#TopicPreprocessorDirectivesPerformance',1,'']]],
  ['vectorization_20how_20do_20i_20get_20rid_20of_20that_20stuff_76',['I don&apos;t care about optimal vectorization, how do I get rid of that stuff?',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/UnalignedArrayAssert.dox#getrid',1,'']]],
  ['vectorization_5flogic_77',['vectorization_logic',['../structvectorization__logic.html',1,'']]],
  ['vectorization_5flogic_3c_20scalar_2c_20false_20_3e_78',['vectorization_logic&lt; Scalar, false &gt;',['../structvectorization__logic_3_01_scalar_00_01false_01_4.html',1,'']]],
  ['vectorization_5flogic_5fhalf_79',['vectorization_logic_half',['../structvectorization__logic__half.html',1,'']]],
  ['vectorization_5flogic_5fhalf_3c_20scalar_2c_20false_20_3e_80',['vectorization_logic_half&lt; Scalar, false &gt;',['../structvectorization__logic__half_3_01_scalar_00_01false_01_4.html',1,'']]],
  ['vectorize_5farg_81',['vectorize_arg',['../structvectorize__arg.html',1,'']]],
  ['vectorize_5fhelper_82',['vectorize_helper',['../structvectorize__helper.html',1,'']]],
  ['vectors_83',['vectors',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialBlockOperations.dox#TutorialBlockOperationsSyntaxVectors',1,'Block operations for vectors'],['../_topic_inside_eigen_example.html#ConstructingVectors',1,'Constructing vectors'],['../_getting_started.html#GettingStartedExample2',1,'Example 2: Matrices and vectors'],['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialMatrixClass.dox#TutorialMatrixVectors',1,'Vectors'],['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/StructHavingEigenMembers.dox#StructHavingEigenMembers_dynamicsize',1,'What about dynamic-size matrices and vectors?']]],
  ['vectortype_84',['vectortype',['../class_eigen_1_1_transform.html#aaeb4ae2f95c8edb0655fd84ab3f89e79',1,'Eigen::Transform::VectorType'],['../class_eigen_1_1_translation.html#a339e17dfec5394ae563f62cca0df451f',1,'Eigen::Translation::VectorType'],['../class_eigen_1_1_generalized_eigen_solver.html#a5aa3d1390c2b0d455c1c9b8b3101b119',1,'Eigen::GeneralizedEigenSolver::VectorType'],['../struct_vector_type.html',1,'VectorType&lt; Container, Scalar &gt;']]],
  ['vectortype_3c_20eigenvectorcontainer_2c_20scalar_20_3e_85',['VectorType&lt; EigenVectorContainer, Scalar &gt;',['../struct_vector_type_3_01_eigen_vector_container_00_01_scalar_01_4.html',1,'']]],
  ['vectortype_3c_20stdvectorcontainer_2c_20scalar_20_3e_86',['VectorType&lt; StdVectorContainer, Scalar &gt;',['../struct_vector_type_3_01_std_vector_container_00_01_scalar_01_4.html',1,'']]],
  ['vectorwise_5freverse_5finplace_5fimpl_87',['vectorwise_reverse_inplace_impl',['../struct_eigen_1_1internal_1_1vectorwise__reverse__inplace__impl.html',1,'Eigen::internal']]],
  ['vectorwise_5freverse_5finplace_5fimpl_3c_20horizontal_20_3e_88',['vectorwise_reverse_inplace_impl&lt; Horizontal &gt;',['../struct_eigen_1_1internal_1_1vectorwise__reverse__inplace__impl_3_01_horizontal_01_4.html',1,'Eigen::internal']]],
  ['vectorwise_5freverse_5finplace_5fimpl_3c_20vertical_20_3e_89',['vectorwise_reverse_inplace_impl&lt; Vertical &gt;',['../struct_eigen_1_1internal_1_1vectorwise__reverse__inplace__impl_3_01_vertical_01_4.html',1,'Eigen::internal']]],
  ['vectorwiseop_90',['VectorwiseOp',['../class_eigen_1_1_vectorwise_op.html',1,'Eigen']]],
  ['vectorxf_91',['VectorXf',['../nanogui_2include_2nanogui_2common_8h.html#ab1cfd56887f8138b4277d25817402296',1,'common.h']]],
  ['version_92',['version',['../intro_guide.html#intro_version_compile',1,'Compile-time version'],['../intro_guide.html#intro_version_runtime',1,'Run-time version'],['../struct_g_l_shader_1_1_buffer.html#a9aacde5b0e0c690b60d9b6899c5700ff',1,'GLShader::Buffer::version']]],
  ['version_203_204_93',['version 3 4',['../news.html#caveats',1,'Caveats for version 3.4'],['../news.html#deprecations_34',1,'Deprecations in version 3.4'],['../news.html#constants_34',1,'New constants in version 3.4'],['../news.html#features_34',1,'New features in version 3.4'],['../news.html#functions_34',1,'New functions in version 3.4'],['../news.html#symbols_34',1,'New symbols in version 3.4'],['../news.html#types_34',1,'New types in version 3.4'],['../news.html#news_34',1,'Release notes for version 3.4']]],
  ['version_20and_20error_20reference_94',['Initialization, version and error reference',['../group__init.html',1,'']]],
  ['version_20compatibility_95',['Version compatibility',['../intro_guide.html#compatibility',1,'']]],
  ['version_20management_96',['Version management',['../intro_guide.html#intro_version',1,'']]],
  ['version_20string_97',['Version string',['../intro_guide.html#intro_version_string',1,'']]],
  ['version_20string_20format_20has_20been_20changed_98',['Version string format has been changed',['../news.html#version_string_34',1,'']]],
  ['versions_99',['Release notes for earlier versions',['../news.html#news_archive',1,'']]],
  ['versions_20of_20windows_20older_20than_20xp_100',['Support for versions of Windows older than XP',['../moving_guide.html#moving_windows',1,'']]],
  ['vertex_101',['Vertex',['../struct_vertex.html',1,'']]],
  ['vertex_5ft_102',['vertex_t',['../structvertex__t.html',1,'']]],
  ['vertical_103',['vertical',['../layout_8h.html#a871118a09520247c78a71ecd7b0abd58a06ce2a25e5d12c166a36f654dbea6012',1,'Vertical:&#160;layout.h'],['../group__enums.html#ggad49a7b3738e273eb00932271b36127f7ae2efac6e74ecab5e3b0b1561c5ddf83e',1,'Eigen::Vertical']]],
  ['via_20nullary_20expressions_104',['Matrix manipulation via nullary-expressions',['../_topic_customizing__nullary_expr.html',1,'UserManual_CustomizingEigen']]],
  ['video_20mode_20bug_105',['Reporting a monitor or video mode bug',['../md_3rdparty_2glfw_2docs_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md20',1,'']]],
  ['video_20mode_20enumeration_106',['Video mode enumeration',['../moving_guide.html#moving_video_modes',1,'']]],
  ['video_20modes_107',['Video modes',['../monitor_guide.html#monitor_modes',1,'']]],
  ['viewascholmod_108',['viewascholmod',['../namespace_eigen.html#ac9fb9e40cfc9ddbdc7da84ee01bb7545',1,'Eigen::viewAsCholmod(Ref&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt; mat)'],['../namespace_eigen.html#afacb818b18280e2e1ab73836ab74cab5',1,'Eigen::viewAsCholmod(const SparseSelfAdjointView&lt; const SparseMatrix&lt; _Scalar, _Options, _Index &gt;, UpLo &gt; &amp;mat)'],['../namespace_eigen.html#a92fe7b595099051fa1d1c443641a6de3',1,'Eigen::viewAsCholmod(MatrixBase&lt; Derived &gt; &amp;mat)']]],
  ['viewaseigen_109',['viewAsEigen',['../namespace_eigen.html#af13cf1742b9a7a03703e8e5393bb6f86',1,'Eigen']]],
  ['views_110',['views',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/QuickReference.dox#QuickRef_SelfadjointMatrix',1,'Symmetric/selfadjoint views'],['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialSparse.dox#TutorialSparse_TriangularSelfadjoint',1,'Triangular and selfadjoint views'],['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/QuickReference.dox#QuickRef_TriangularView',1,'Triangular views']]],
  ['virtual_20position_111',['Virtual position',['../monitor_guide.html#monitor_pos',1,'']]],
  ['visibility_112',['Window visibility',['../window_guide.html#window_hide',1,'']]],
  ['visible_113',['visible',['../class_widget.html#a5aadbf5207a17eb0f12e8bab5ada9c02',1,'Widget']]],
  ['visiblebuttonarea_114',['visibleButtonArea',['../class_tab_header.html#a023950bb06e9fc2d46c4bab5a6fdb5d1',1,'TabHeader']]],
  ['visiblerecursive_115',['visibleRecursive',['../class_widget.html#aac494cf2c5342c42945384e930a8ce3a',1,'Widget']]],
  ['visit_116',['visit',['../class_eigen_1_1_dense_base.html#a7f73df3954a09c7ab0dca208b6b23ddd',1,'Eigen::DenseBase']]],
  ['visit_5fhelper_117',['visit_helper',['../structvisit__helper.html',1,'']]],
  ['visitor_5fevaluator_118',['visitor_evaluator',['../class_eigen_1_1internal_1_1visitor__evaluator.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_119',['visitor_impl',['../struct_eigen_1_1internal_1_1visitor__impl.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_3c_20visitor_2c_20derived_2c_201_20_3e_120',['visitor_impl&lt; Visitor, Derived, 1 &gt;',['../struct_eigen_1_1internal_1_1visitor__impl_3_01_visitor_00_01_derived_00_011_01_4.html',1,'Eigen::internal']]],
  ['visitor_5fimpl_3c_20visitor_2c_20derived_2c_20dynamic_20_3e_121',['visitor_impl&lt; Visitor, Derived, Dynamic &gt;',['../struct_eigen_1_1internal_1_1visitor__impl_3_01_visitor_00_01_derived_00_01_dynamic_01_4.html',1,'Eigen::internal']]],
  ['visitors_122',['Visitors',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialReductionsVisitorsBroadcasting.dox#TutorialReductionsVisitorsBroadcastingVisitors',1,'']]],
  ['visual_20c_20on_20windows_123',['visual c on windows',['../compile_guide.html#compile_deps_msvc',1,'Dependencies for Visual C++ on Windows'],['../build_guide.html#build_link_win32',1,'With MinGW or Visual C++ on Windows']]],
  ['vkacquirenextimageinfokhr_124',['VkAcquireNextImageInfoKHR',['../struct_vk_acquire_next_image_info_k_h_r.html',1,'']]],
  ['vkallocationcallbacks_125',['VkAllocationCallbacks',['../struct_vk_allocation_callbacks.html',1,'']]],
  ['vkapplicationinfo_126',['VkApplicationInfo',['../struct_vk_application_info.html',1,'']]],
  ['vkattachmentdescription_127',['VkAttachmentDescription',['../struct_vk_attachment_description.html',1,'']]],
  ['vkattachmentdescription2_128',['VkAttachmentDescription2',['../struct_vk_attachment_description2.html',1,'']]],
  ['vkattachmentdescriptionstencillayout_129',['VkAttachmentDescriptionStencilLayout',['../struct_vk_attachment_description_stencil_layout.html',1,'']]],
  ['vkattachmentreference_130',['VkAttachmentReference',['../struct_vk_attachment_reference.html',1,'']]],
  ['vkattachmentreference2_131',['VkAttachmentReference2',['../struct_vk_attachment_reference2.html',1,'']]],
  ['vkattachmentreferencestencillayout_132',['VkAttachmentReferenceStencilLayout',['../struct_vk_attachment_reference_stencil_layout.html',1,'']]],
  ['vkbaseinstructure_133',['VkBaseInStructure',['../struct_vk_base_in_structure.html',1,'']]],
  ['vkbaseoutstructure_134',['VkBaseOutStructure',['../struct_vk_base_out_structure.html',1,'']]],
  ['vkbindbuffermemorydevicegroupinfo_135',['VkBindBufferMemoryDeviceGroupInfo',['../struct_vk_bind_buffer_memory_device_group_info.html',1,'']]],
  ['vkbindbuffermemoryinfo_136',['VkBindBufferMemoryInfo',['../struct_vk_bind_buffer_memory_info.html',1,'']]],
  ['vkbindimagememorydevicegroupinfo_137',['VkBindImageMemoryDeviceGroupInfo',['../struct_vk_bind_image_memory_device_group_info.html',1,'']]],
  ['vkbindimagememoryinfo_138',['VkBindImageMemoryInfo',['../struct_vk_bind_image_memory_info.html',1,'']]],
  ['vkbindimagememoryswapchaininfokhr_139',['VkBindImageMemorySwapchainInfoKHR',['../struct_vk_bind_image_memory_swapchain_info_k_h_r.html',1,'']]],
  ['vkbindimageplanememoryinfo_140',['VkBindImagePlaneMemoryInfo',['../struct_vk_bind_image_plane_memory_info.html',1,'']]],
  ['vkbindsparseinfo_141',['VkBindSparseInfo',['../struct_vk_bind_sparse_info.html',1,'']]],
  ['vkblitimageinfo2_142',['VkBlitImageInfo2',['../struct_vk_blit_image_info2.html',1,'']]],
  ['vkbuffercopy_143',['VkBufferCopy',['../struct_vk_buffer_copy.html',1,'']]],
  ['vkbuffercopy2_144',['VkBufferCopy2',['../struct_vk_buffer_copy2.html',1,'']]],
  ['vkbuffercreateinfo_145',['VkBufferCreateInfo',['../struct_vk_buffer_create_info.html',1,'']]],
  ['vkbufferdeviceaddressinfo_146',['VkBufferDeviceAddressInfo',['../struct_vk_buffer_device_address_info.html',1,'']]],
  ['vkbufferimagecopy_147',['VkBufferImageCopy',['../struct_vk_buffer_image_copy.html',1,'']]],
  ['vkbufferimagecopy2_148',['VkBufferImageCopy2',['../struct_vk_buffer_image_copy2.html',1,'']]],
  ['vkbuffermemorybarrier_149',['VkBufferMemoryBarrier',['../struct_vk_buffer_memory_barrier.html',1,'']]],
  ['vkbuffermemorybarrier2_150',['VkBufferMemoryBarrier2',['../struct_vk_buffer_memory_barrier2.html',1,'']]],
  ['vkbuffermemoryrequirementsinfo2_151',['VkBufferMemoryRequirementsInfo2',['../struct_vk_buffer_memory_requirements_info2.html',1,'']]],
  ['vkbufferopaquecaptureaddresscreateinfo_152',['VkBufferOpaqueCaptureAddressCreateInfo',['../struct_vk_buffer_opaque_capture_address_create_info.html',1,'']]],
  ['vkbufferviewcreateinfo_153',['VkBufferViewCreateInfo',['../struct_vk_buffer_view_create_info.html',1,'']]],
  ['vkclearattachment_154',['VkClearAttachment',['../struct_vk_clear_attachment.html',1,'']]],
  ['vkclearcolorvalue_155',['VkClearColorValue',['../union_vk_clear_color_value.html',1,'']]],
  ['vkcleardepthstencilvalue_156',['VkClearDepthStencilValue',['../struct_vk_clear_depth_stencil_value.html',1,'']]],
  ['vkclearrect_157',['VkClearRect',['../struct_vk_clear_rect.html',1,'']]],
  ['vkclearvalue_158',['VkClearValue',['../union_vk_clear_value.html',1,'']]],
  ['vkcommandbufferallocateinfo_159',['VkCommandBufferAllocateInfo',['../struct_vk_command_buffer_allocate_info.html',1,'']]],
  ['vkcommandbufferbegininfo_160',['VkCommandBufferBeginInfo',['../struct_vk_command_buffer_begin_info.html',1,'']]],
  ['vkcommandbufferinheritanceinfo_161',['VkCommandBufferInheritanceInfo',['../struct_vk_command_buffer_inheritance_info.html',1,'']]],
  ['vkcommandbufferinheritancerenderinginfo_162',['VkCommandBufferInheritanceRenderingInfo',['../struct_vk_command_buffer_inheritance_rendering_info.html',1,'']]],
  ['vkcommandbuffersubmitinfo_163',['VkCommandBufferSubmitInfo',['../struct_vk_command_buffer_submit_info.html',1,'']]],
  ['vkcommandpoolcreateinfo_164',['VkCommandPoolCreateInfo',['../struct_vk_command_pool_create_info.html',1,'']]],
  ['vkcomponentmapping_165',['VkComponentMapping',['../struct_vk_component_mapping.html',1,'']]],
  ['vkcomputepipelinecreateinfo_166',['VkComputePipelineCreateInfo',['../struct_vk_compute_pipeline_create_info.html',1,'']]],
  ['vkconformanceversion_167',['VkConformanceVersion',['../struct_vk_conformance_version.html',1,'']]],
  ['vkcopybufferinfo2_168',['VkCopyBufferInfo2',['../struct_vk_copy_buffer_info2.html',1,'']]],
  ['vkcopybuffertoimageinfo2_169',['VkCopyBufferToImageInfo2',['../struct_vk_copy_buffer_to_image_info2.html',1,'']]],
  ['vkcopydescriptorset_170',['VkCopyDescriptorSet',['../struct_vk_copy_descriptor_set.html',1,'']]],
  ['vkcopyimageinfo2_171',['VkCopyImageInfo2',['../struct_vk_copy_image_info2.html',1,'']]],
  ['vkcopyimagetobufferinfo2_172',['VkCopyImageToBufferInfo2',['../struct_vk_copy_image_to_buffer_info2.html',1,'']]],
  ['vkdebugreportcallbackcreateinfoext_173',['VkDebugReportCallbackCreateInfoEXT',['../struct_vk_debug_report_callback_create_info_e_x_t.html',1,'']]],
  ['vkdependencyinfo_174',['VkDependencyInfo',['../struct_vk_dependency_info.html',1,'']]],
  ['vkdescriptorbufferinfo_175',['VkDescriptorBufferInfo',['../struct_vk_descriptor_buffer_info.html',1,'']]],
  ['vkdescriptorimageinfo_176',['VkDescriptorImageInfo',['../struct_vk_descriptor_image_info.html',1,'']]],
  ['vkdescriptorpoolcreateinfo_177',['VkDescriptorPoolCreateInfo',['../struct_vk_descriptor_pool_create_info.html',1,'']]],
  ['vkdescriptorpoolinlineuniformblockcreateinfo_178',['VkDescriptorPoolInlineUniformBlockCreateInfo',['../struct_vk_descriptor_pool_inline_uniform_block_create_info.html',1,'']]],
  ['vkdescriptorpoolsize_179',['VkDescriptorPoolSize',['../struct_vk_descriptor_pool_size.html',1,'']]],
  ['vkdescriptorsetallocateinfo_180',['VkDescriptorSetAllocateInfo',['../struct_vk_descriptor_set_allocate_info.html',1,'']]],
  ['vkdescriptorsetlayoutbinding_181',['VkDescriptorSetLayoutBinding',['../struct_vk_descriptor_set_layout_binding.html',1,'']]],
  ['vkdescriptorsetlayoutbindingflagscreateinfo_182',['VkDescriptorSetLayoutBindingFlagsCreateInfo',['../struct_vk_descriptor_set_layout_binding_flags_create_info.html',1,'']]],
  ['vkdescriptorsetlayoutcreateinfo_183',['VkDescriptorSetLayoutCreateInfo',['../struct_vk_descriptor_set_layout_create_info.html',1,'']]],
  ['vkdescriptorsetlayoutsupport_184',['VkDescriptorSetLayoutSupport',['../struct_vk_descriptor_set_layout_support.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountallocateinfo_185',['VkDescriptorSetVariableDescriptorCountAllocateInfo',['../struct_vk_descriptor_set_variable_descriptor_count_allocate_info.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountlayoutsupport_186',['VkDescriptorSetVariableDescriptorCountLayoutSupport',['../struct_vk_descriptor_set_variable_descriptor_count_layout_support.html',1,'']]],
  ['vkdescriptorupdatetemplatecreateinfo_187',['VkDescriptorUpdateTemplateCreateInfo',['../struct_vk_descriptor_update_template_create_info.html',1,'']]],
  ['vkdescriptorupdatetemplateentry_188',['VkDescriptorUpdateTemplateEntry',['../struct_vk_descriptor_update_template_entry.html',1,'']]],
  ['vkdevicebuffermemoryrequirements_189',['VkDeviceBufferMemoryRequirements',['../struct_vk_device_buffer_memory_requirements.html',1,'']]],
  ['vkdevicecreateinfo_190',['VkDeviceCreateInfo',['../struct_vk_device_create_info.html',1,'']]],
  ['vkdevicegroupbindsparseinfo_191',['VkDeviceGroupBindSparseInfo',['../struct_vk_device_group_bind_sparse_info.html',1,'']]],
  ['vkdevicegroupcommandbufferbegininfo_192',['VkDeviceGroupCommandBufferBeginInfo',['../struct_vk_device_group_command_buffer_begin_info.html',1,'']]],
  ['vkdevicegroupdevicecreateinfo_193',['VkDeviceGroupDeviceCreateInfo',['../struct_vk_device_group_device_create_info.html',1,'']]],
  ['vkdevicegrouppresentcapabilitieskhr_194',['VkDeviceGroupPresentCapabilitiesKHR',['../struct_vk_device_group_present_capabilities_k_h_r.html',1,'']]],
  ['vkdevicegrouppresentinfokhr_195',['VkDeviceGroupPresentInfoKHR',['../struct_vk_device_group_present_info_k_h_r.html',1,'']]],
  ['vkdevicegrouprenderpassbegininfo_196',['VkDeviceGroupRenderPassBeginInfo',['../struct_vk_device_group_render_pass_begin_info.html',1,'']]],
  ['vkdevicegroupsubmitinfo_197',['VkDeviceGroupSubmitInfo',['../struct_vk_device_group_submit_info.html',1,'']]],
  ['vkdevicegroupswapchaincreateinfokhr_198',['VkDeviceGroupSwapchainCreateInfoKHR',['../struct_vk_device_group_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkdeviceimagememoryrequirements_199',['VkDeviceImageMemoryRequirements',['../struct_vk_device_image_memory_requirements.html',1,'']]],
  ['vkdevicememoryopaquecaptureaddressinfo_200',['VkDeviceMemoryOpaqueCaptureAddressInfo',['../struct_vk_device_memory_opaque_capture_address_info.html',1,'']]],
  ['vkdeviceprivatedatacreateinfo_201',['VkDevicePrivateDataCreateInfo',['../struct_vk_device_private_data_create_info.html',1,'']]],
  ['vkdevicequeuecreateinfo_202',['VkDeviceQueueCreateInfo',['../struct_vk_device_queue_create_info.html',1,'']]],
  ['vkdevicequeueinfo2_203',['VkDeviceQueueInfo2',['../struct_vk_device_queue_info2.html',1,'']]],
  ['vkdispatchindirectcommand_204',['VkDispatchIndirectCommand',['../struct_vk_dispatch_indirect_command.html',1,'']]],
  ['vkdisplaymodecreateinfokhr_205',['VkDisplayModeCreateInfoKHR',['../struct_vk_display_mode_create_info_k_h_r.html',1,'']]],
  ['vkdisplaymodeparameterskhr_206',['VkDisplayModeParametersKHR',['../struct_vk_display_mode_parameters_k_h_r.html',1,'']]],
  ['vkdisplaymodepropertieskhr_207',['VkDisplayModePropertiesKHR',['../struct_vk_display_mode_properties_k_h_r.html',1,'']]],
  ['vkdisplayplanecapabilitieskhr_208',['VkDisplayPlaneCapabilitiesKHR',['../struct_vk_display_plane_capabilities_k_h_r.html',1,'']]],
  ['vkdisplayplanepropertieskhr_209',['VkDisplayPlanePropertiesKHR',['../struct_vk_display_plane_properties_k_h_r.html',1,'']]],
  ['vkdisplaypresentinfokhr_210',['VkDisplayPresentInfoKHR',['../struct_vk_display_present_info_k_h_r.html',1,'']]],
  ['vkdisplaypropertieskhr_211',['VkDisplayPropertiesKHR',['../struct_vk_display_properties_k_h_r.html',1,'']]],
  ['vkdisplaysurfacecreateinfokhr_212',['VkDisplaySurfaceCreateInfoKHR',['../struct_vk_display_surface_create_info_k_h_r.html',1,'']]],
  ['vkdrawindexedindirectcommand_213',['VkDrawIndexedIndirectCommand',['../struct_vk_draw_indexed_indirect_command.html',1,'']]],
  ['vkdrawindirectcommand_214',['VkDrawIndirectCommand',['../struct_vk_draw_indirect_command.html',1,'']]],
  ['vkeventcreateinfo_215',['VkEventCreateInfo',['../struct_vk_event_create_info.html',1,'']]],
  ['vkexportfencecreateinfo_216',['VkExportFenceCreateInfo',['../struct_vk_export_fence_create_info.html',1,'']]],
  ['vkexportmemoryallocateinfo_217',['VkExportMemoryAllocateInfo',['../struct_vk_export_memory_allocate_info.html',1,'']]],
  ['vkexportsemaphorecreateinfo_218',['VkExportSemaphoreCreateInfo',['../struct_vk_export_semaphore_create_info.html',1,'']]],
  ['vkextensionproperties_219',['VkExtensionProperties',['../struct_vk_extension_properties.html',1,'']]],
  ['vkextent2d_220',['VkExtent2D',['../struct_vk_extent2_d.html',1,'']]],
  ['vkextent3d_221',['VkExtent3D',['../struct_vk_extent3_d.html',1,'']]],
  ['vkexternalbufferproperties_222',['VkExternalBufferProperties',['../struct_vk_external_buffer_properties.html',1,'']]],
  ['vkexternalfenceproperties_223',['VkExternalFenceProperties',['../struct_vk_external_fence_properties.html',1,'']]],
  ['vkexternalimageformatproperties_224',['VkExternalImageFormatProperties',['../struct_vk_external_image_format_properties.html',1,'']]],
  ['vkexternalmemorybuffercreateinfo_225',['VkExternalMemoryBufferCreateInfo',['../struct_vk_external_memory_buffer_create_info.html',1,'']]],
  ['vkexternalmemoryimagecreateinfo_226',['VkExternalMemoryImageCreateInfo',['../struct_vk_external_memory_image_create_info.html',1,'']]],
  ['vkexternalmemoryproperties_227',['VkExternalMemoryProperties',['../struct_vk_external_memory_properties.html',1,'']]],
  ['vkexternalsemaphoreproperties_228',['VkExternalSemaphoreProperties',['../struct_vk_external_semaphore_properties.html',1,'']]],
  ['vkfencecreateinfo_229',['VkFenceCreateInfo',['../struct_vk_fence_create_info.html',1,'']]],
  ['vkformatproperties_230',['VkFormatProperties',['../struct_vk_format_properties.html',1,'']]],
  ['vkformatproperties2_231',['VkFormatProperties2',['../struct_vk_format_properties2.html',1,'']]],
  ['vkformatproperties3_232',['VkFormatProperties3',['../struct_vk_format_properties3.html',1,'']]],
  ['vkframebufferattachmentimageinfo_233',['VkFramebufferAttachmentImageInfo',['../struct_vk_framebuffer_attachment_image_info.html',1,'']]],
  ['vkframebufferattachmentscreateinfo_234',['VkFramebufferAttachmentsCreateInfo',['../struct_vk_framebuffer_attachments_create_info.html',1,'']]],
  ['vkframebuffercreateinfo_235',['VkFramebufferCreateInfo',['../struct_vk_framebuffer_create_info.html',1,'']]],
  ['vkgraphicspipelinecreateinfo_236',['VkGraphicsPipelineCreateInfo',['../struct_vk_graphics_pipeline_create_info.html',1,'']]],
  ['vkimageblit_237',['VkImageBlit',['../struct_vk_image_blit.html',1,'']]],
  ['vkimageblit2_238',['VkImageBlit2',['../struct_vk_image_blit2.html',1,'']]],
  ['vkimagecopy_239',['VkImageCopy',['../struct_vk_image_copy.html',1,'']]],
  ['vkimagecopy2_240',['VkImageCopy2',['../struct_vk_image_copy2.html',1,'']]],
  ['vkimagecreateinfo_241',['VkImageCreateInfo',['../struct_vk_image_create_info.html',1,'']]],
  ['vkimageformatlistcreateinfo_242',['VkImageFormatListCreateInfo',['../struct_vk_image_format_list_create_info.html',1,'']]],
  ['vkimageformatproperties_243',['VkImageFormatProperties',['../struct_vk_image_format_properties.html',1,'']]],
  ['vkimageformatproperties2_244',['VkImageFormatProperties2',['../struct_vk_image_format_properties2.html',1,'']]],
  ['vkimagememorybarrier_245',['VkImageMemoryBarrier',['../struct_vk_image_memory_barrier.html',1,'']]],
  ['vkimagememorybarrier2_246',['VkImageMemoryBarrier2',['../struct_vk_image_memory_barrier2.html',1,'']]],
  ['vkimagememoryrequirementsinfo2_247',['VkImageMemoryRequirementsInfo2',['../struct_vk_image_memory_requirements_info2.html',1,'']]],
  ['vkimageplanememoryrequirementsinfo_248',['VkImagePlaneMemoryRequirementsInfo',['../struct_vk_image_plane_memory_requirements_info.html',1,'']]],
  ['vkimageresolve_249',['VkImageResolve',['../struct_vk_image_resolve.html',1,'']]],
  ['vkimageresolve2_250',['VkImageResolve2',['../struct_vk_image_resolve2.html',1,'']]],
  ['vkimagesparsememoryrequirementsinfo2_251',['VkImageSparseMemoryRequirementsInfo2',['../struct_vk_image_sparse_memory_requirements_info2.html',1,'']]],
  ['vkimagestencilusagecreateinfo_252',['VkImageStencilUsageCreateInfo',['../struct_vk_image_stencil_usage_create_info.html',1,'']]],
  ['vkimagesubresource_253',['VkImageSubresource',['../struct_vk_image_subresource.html',1,'']]],
  ['vkimagesubresourcelayers_254',['VkImageSubresourceLayers',['../struct_vk_image_subresource_layers.html',1,'']]],
  ['vkimagesubresourcerange_255',['VkImageSubresourceRange',['../struct_vk_image_subresource_range.html',1,'']]],
  ['vkimageswapchaincreateinfokhr_256',['VkImageSwapchainCreateInfoKHR',['../struct_vk_image_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkimageviewcreateinfo_257',['VkImageViewCreateInfo',['../struct_vk_image_view_create_info.html',1,'']]],
  ['vkimageviewusagecreateinfo_258',['VkImageViewUsageCreateInfo',['../struct_vk_image_view_usage_create_info.html',1,'']]],
  ['vkinputattachmentaspectreference_259',['VkInputAttachmentAspectReference',['../struct_vk_input_attachment_aspect_reference.html',1,'']]],
  ['vkinstancecreateinfo_260',['VkInstanceCreateInfo',['../struct_vk_instance_create_info.html',1,'']]],
  ['vklayerproperties_261',['VkLayerProperties',['../struct_vk_layer_properties.html',1,'']]],
  ['vkmacossurfacecreateinfomvk_262',['VkMacOSSurfaceCreateInfoMVK',['../struct_vk_mac_o_s_surface_create_info_m_v_k.html',1,'']]],
  ['vkmappedmemoryrange_263',['VkMappedMemoryRange',['../struct_vk_mapped_memory_range.html',1,'']]],
  ['vkmemoryallocateflagsinfo_264',['VkMemoryAllocateFlagsInfo',['../struct_vk_memory_allocate_flags_info.html',1,'']]],
  ['vkmemoryallocateinfo_265',['VkMemoryAllocateInfo',['../struct_vk_memory_allocate_info.html',1,'']]],
  ['vkmemorybarrier_266',['VkMemoryBarrier',['../struct_vk_memory_barrier.html',1,'']]],
  ['vkmemorybarrier2_267',['VkMemoryBarrier2',['../struct_vk_memory_barrier2.html',1,'']]],
  ['vkmemorydedicatedallocateinfo_268',['VkMemoryDedicatedAllocateInfo',['../struct_vk_memory_dedicated_allocate_info.html',1,'']]],
  ['vkmemorydedicatedrequirements_269',['VkMemoryDedicatedRequirements',['../struct_vk_memory_dedicated_requirements.html',1,'']]],
  ['vkmemoryheap_270',['VkMemoryHeap',['../struct_vk_memory_heap.html',1,'']]],
  ['vkmemoryopaquecaptureaddressallocateinfo_271',['VkMemoryOpaqueCaptureAddressAllocateInfo',['../struct_vk_memory_opaque_capture_address_allocate_info.html',1,'']]],
  ['vkmemoryrequirements_272',['VkMemoryRequirements',['../struct_vk_memory_requirements.html',1,'']]],
  ['vkmemoryrequirements2_273',['VkMemoryRequirements2',['../struct_vk_memory_requirements2.html',1,'']]],
  ['vkmemorytype_274',['VkMemoryType',['../struct_vk_memory_type.html',1,'']]],
  ['vkmetalsurfacecreateinfoext_275',['VkMetalSurfaceCreateInfoEXT',['../struct_vk_metal_surface_create_info_e_x_t.html',1,'']]],
  ['vkmirsurfacecreateinfokhr_276',['VkMirSurfaceCreateInfoKHR',['../struct_vk_mir_surface_create_info_k_h_r.html',1,'']]],
  ['vkoffset2d_277',['VkOffset2D',['../struct_vk_offset2_d.html',1,'']]],
  ['vkoffset3d_278',['VkOffset3D',['../struct_vk_offset3_d.html',1,'']]],
  ['vkphysicaldevice16bitstoragefeatures_279',['VkPhysicalDevice16BitStorageFeatures',['../struct_vk_physical_device16_bit_storage_features.html',1,'']]],
  ['vkphysicaldevice8bitstoragefeatures_280',['VkPhysicalDevice8BitStorageFeatures',['../struct_vk_physical_device8_bit_storage_features.html',1,'']]],
  ['vkphysicaldevicebufferdeviceaddressfeatures_281',['VkPhysicalDeviceBufferDeviceAddressFeatures',['../struct_vk_physical_device_buffer_device_address_features.html',1,'']]],
  ['vkphysicaldevicedepthstencilresolveproperties_282',['VkPhysicalDeviceDepthStencilResolveProperties',['../struct_vk_physical_device_depth_stencil_resolve_properties.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingfeatures_283',['VkPhysicalDeviceDescriptorIndexingFeatures',['../struct_vk_physical_device_descriptor_indexing_features.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingproperties_284',['VkPhysicalDeviceDescriptorIndexingProperties',['../struct_vk_physical_device_descriptor_indexing_properties.html',1,'']]],
  ['vkphysicaldevicedriverproperties_285',['VkPhysicalDeviceDriverProperties',['../struct_vk_physical_device_driver_properties.html',1,'']]],
  ['vkphysicaldevicedynamicrenderingfeatures_286',['VkPhysicalDeviceDynamicRenderingFeatures',['../struct_vk_physical_device_dynamic_rendering_features.html',1,'']]],
  ['vkphysicaldeviceexternalbufferinfo_287',['VkPhysicalDeviceExternalBufferInfo',['../struct_vk_physical_device_external_buffer_info.html',1,'']]],
  ['vkphysicaldeviceexternalfenceinfo_288',['VkPhysicalDeviceExternalFenceInfo',['../struct_vk_physical_device_external_fence_info.html',1,'']]],
  ['vkphysicaldeviceexternalimageformatinfo_289',['VkPhysicalDeviceExternalImageFormatInfo',['../struct_vk_physical_device_external_image_format_info.html',1,'']]],
  ['vkphysicaldeviceexternalsemaphoreinfo_290',['VkPhysicalDeviceExternalSemaphoreInfo',['../struct_vk_physical_device_external_semaphore_info.html',1,'']]],
  ['vkphysicaldevicefeatures_291',['VkPhysicalDeviceFeatures',['../struct_vk_physical_device_features.html',1,'']]],
  ['vkphysicaldevicefeatures2_292',['VkPhysicalDeviceFeatures2',['../struct_vk_physical_device_features2.html',1,'']]],
  ['vkphysicaldevicefloatcontrolsproperties_293',['VkPhysicalDeviceFloatControlsProperties',['../struct_vk_physical_device_float_controls_properties.html',1,'']]],
  ['vkphysicaldevicegroupproperties_294',['VkPhysicalDeviceGroupProperties',['../struct_vk_physical_device_group_properties.html',1,'']]],
  ['vkphysicaldevicehostqueryresetfeatures_295',['VkPhysicalDeviceHostQueryResetFeatures',['../struct_vk_physical_device_host_query_reset_features.html',1,'']]],
  ['vkphysicaldeviceidproperties_296',['VkPhysicalDeviceIDProperties',['../struct_vk_physical_device_i_d_properties.html',1,'']]],
  ['vkphysicaldeviceimageformatinfo2_297',['VkPhysicalDeviceImageFormatInfo2',['../struct_vk_physical_device_image_format_info2.html',1,'']]],
  ['vkphysicaldeviceimagelessframebufferfeatures_298',['VkPhysicalDeviceImagelessFramebufferFeatures',['../struct_vk_physical_device_imageless_framebuffer_features.html',1,'']]],
  ['vkphysicaldeviceimagerobustnessfeatures_299',['VkPhysicalDeviceImageRobustnessFeatures',['../struct_vk_physical_device_image_robustness_features.html',1,'']]],
  ['vkphysicaldeviceinlineuniformblockfeatures_300',['VkPhysicalDeviceInlineUniformBlockFeatures',['../struct_vk_physical_device_inline_uniform_block_features.html',1,'']]],
  ['vkphysicaldeviceinlineuniformblockproperties_301',['VkPhysicalDeviceInlineUniformBlockProperties',['../struct_vk_physical_device_inline_uniform_block_properties.html',1,'']]],
  ['vkphysicaldevicelimits_302',['VkPhysicalDeviceLimits',['../struct_vk_physical_device_limits.html',1,'']]],
  ['vkphysicaldevicemaintenance3properties_303',['VkPhysicalDeviceMaintenance3Properties',['../struct_vk_physical_device_maintenance3_properties.html',1,'']]],
  ['vkphysicaldevicemaintenance4features_304',['VkPhysicalDeviceMaintenance4Features',['../struct_vk_physical_device_maintenance4_features.html',1,'']]],
  ['vkphysicaldevicemaintenance4properties_305',['VkPhysicalDeviceMaintenance4Properties',['../struct_vk_physical_device_maintenance4_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties_306',['VkPhysicalDeviceMemoryProperties',['../struct_vk_physical_device_memory_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties2_307',['VkPhysicalDeviceMemoryProperties2',['../struct_vk_physical_device_memory_properties2.html',1,'']]],
  ['vkphysicaldevicemultiviewfeatures_308',['VkPhysicalDeviceMultiviewFeatures',['../struct_vk_physical_device_multiview_features.html',1,'']]],
  ['vkphysicaldevicemultiviewproperties_309',['VkPhysicalDeviceMultiviewProperties',['../struct_vk_physical_device_multiview_properties.html',1,'']]],
  ['vkphysicaldevicepipelinecreationcachecontrolfeatures_310',['VkPhysicalDevicePipelineCreationCacheControlFeatures',['../struct_vk_physical_device_pipeline_creation_cache_control_features.html',1,'']]],
  ['vkphysicaldevicepointclippingproperties_311',['VkPhysicalDevicePointClippingProperties',['../struct_vk_physical_device_point_clipping_properties.html',1,'']]],
  ['vkphysicaldeviceprivatedatafeatures_312',['VkPhysicalDevicePrivateDataFeatures',['../struct_vk_physical_device_private_data_features.html',1,'']]],
  ['vkphysicaldeviceproperties_313',['VkPhysicalDeviceProperties',['../struct_vk_physical_device_properties.html',1,'']]],
  ['vkphysicaldeviceproperties2_314',['VkPhysicalDeviceProperties2',['../struct_vk_physical_device_properties2.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryfeatures_315',['VkPhysicalDeviceProtectedMemoryFeatures',['../struct_vk_physical_device_protected_memory_features.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryproperties_316',['VkPhysicalDeviceProtectedMemoryProperties',['../struct_vk_physical_device_protected_memory_properties.html',1,'']]],
  ['vkphysicaldevicesamplerfilterminmaxproperties_317',['VkPhysicalDeviceSamplerFilterMinmaxProperties',['../struct_vk_physical_device_sampler_filter_minmax_properties.html',1,'']]],
  ['vkphysicaldevicesamplerycbcrconversionfeatures_318',['VkPhysicalDeviceSamplerYcbcrConversionFeatures',['../struct_vk_physical_device_sampler_ycbcr_conversion_features.html',1,'']]],
  ['vkphysicaldevicescalarblocklayoutfeatures_319',['VkPhysicalDeviceScalarBlockLayoutFeatures',['../struct_vk_physical_device_scalar_block_layout_features.html',1,'']]],
  ['vkphysicaldeviceseparatedepthstencillayoutsfeatures_320',['VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures',['../struct_vk_physical_device_separate_depth_stencil_layouts_features.html',1,'']]],
  ['vkphysicaldeviceshaderatomicint64features_321',['VkPhysicalDeviceShaderAtomicInt64Features',['../struct_vk_physical_device_shader_atomic_int64_features.html',1,'']]],
  ['vkphysicaldeviceshaderdemotetohelperinvocationfeatures_322',['VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures',['../struct_vk_physical_device_shader_demote_to_helper_invocation_features.html',1,'']]],
  ['vkphysicaldeviceshaderdrawparametersfeatures_323',['VkPhysicalDeviceShaderDrawParametersFeatures',['../struct_vk_physical_device_shader_draw_parameters_features.html',1,'']]],
  ['vkphysicaldeviceshaderfloat16int8features_324',['VkPhysicalDeviceShaderFloat16Int8Features',['../struct_vk_physical_device_shader_float16_int8_features.html',1,'']]],
  ['vkphysicaldeviceshaderintegerdotproductfeatures_325',['VkPhysicalDeviceShaderIntegerDotProductFeatures',['../struct_vk_physical_device_shader_integer_dot_product_features.html',1,'']]],
  ['vkphysicaldeviceshaderintegerdotproductproperties_326',['VkPhysicalDeviceShaderIntegerDotProductProperties',['../struct_vk_physical_device_shader_integer_dot_product_properties.html',1,'']]],
  ['vkphysicaldeviceshadersubgroupextendedtypesfeatures_327',['VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures',['../struct_vk_physical_device_shader_subgroup_extended_types_features.html',1,'']]],
  ['vkphysicaldeviceshaderterminateinvocationfeatures_328',['VkPhysicalDeviceShaderTerminateInvocationFeatures',['../struct_vk_physical_device_shader_terminate_invocation_features.html',1,'']]],
  ['vkphysicaldevicesparseimageformatinfo2_329',['VkPhysicalDeviceSparseImageFormatInfo2',['../struct_vk_physical_device_sparse_image_format_info2.html',1,'']]],
  ['vkphysicaldevicesparseproperties_330',['VkPhysicalDeviceSparseProperties',['../struct_vk_physical_device_sparse_properties.html',1,'']]],
  ['vkphysicaldevicesubgroupproperties_331',['VkPhysicalDeviceSubgroupProperties',['../struct_vk_physical_device_subgroup_properties.html',1,'']]],
  ['vkphysicaldevicesubgroupsizecontrolfeatures_332',['VkPhysicalDeviceSubgroupSizeControlFeatures',['../struct_vk_physical_device_subgroup_size_control_features.html',1,'']]],
  ['vkphysicaldevicesubgroupsizecontrolproperties_333',['VkPhysicalDeviceSubgroupSizeControlProperties',['../struct_vk_physical_device_subgroup_size_control_properties.html',1,'']]],
  ['vkphysicaldevicesynchronization2features_334',['VkPhysicalDeviceSynchronization2Features',['../struct_vk_physical_device_synchronization2_features.html',1,'']]],
  ['vkphysicaldevicetexelbufferalignmentproperties_335',['VkPhysicalDeviceTexelBufferAlignmentProperties',['../struct_vk_physical_device_texel_buffer_alignment_properties.html',1,'']]],
  ['vkphysicaldevicetexturecompressionastchdrfeatures_336',['VkPhysicalDeviceTextureCompressionASTCHDRFeatures',['../struct_vk_physical_device_texture_compression_a_s_t_c_h_d_r_features.html',1,'']]],
  ['vkphysicaldevicetimelinesemaphorefeatures_337',['VkPhysicalDeviceTimelineSemaphoreFeatures',['../struct_vk_physical_device_timeline_semaphore_features.html',1,'']]],
  ['vkphysicaldevicetimelinesemaphoreproperties_338',['VkPhysicalDeviceTimelineSemaphoreProperties',['../struct_vk_physical_device_timeline_semaphore_properties.html',1,'']]],
  ['vkphysicaldevicetoolproperties_339',['VkPhysicalDeviceToolProperties',['../struct_vk_physical_device_tool_properties.html',1,'']]],
  ['vkphysicaldeviceuniformbufferstandardlayoutfeatures_340',['VkPhysicalDeviceUniformBufferStandardLayoutFeatures',['../struct_vk_physical_device_uniform_buffer_standard_layout_features.html',1,'']]],
  ['vkphysicaldevicevariablepointersfeatures_341',['VkPhysicalDeviceVariablePointersFeatures',['../struct_vk_physical_device_variable_pointers_features.html',1,'']]],
  ['vkphysicaldevicevulkan11features_342',['VkPhysicalDeviceVulkan11Features',['../struct_vk_physical_device_vulkan11_features.html',1,'']]],
  ['vkphysicaldevicevulkan11properties_343',['VkPhysicalDeviceVulkan11Properties',['../struct_vk_physical_device_vulkan11_properties.html',1,'']]],
  ['vkphysicaldevicevulkan12features_344',['VkPhysicalDeviceVulkan12Features',['../struct_vk_physical_device_vulkan12_features.html',1,'']]],
  ['vkphysicaldevicevulkan12properties_345',['VkPhysicalDeviceVulkan12Properties',['../struct_vk_physical_device_vulkan12_properties.html',1,'']]],
  ['vkphysicaldevicevulkan13features_346',['VkPhysicalDeviceVulkan13Features',['../struct_vk_physical_device_vulkan13_features.html',1,'']]],
  ['vkphysicaldevicevulkan13properties_347',['VkPhysicalDeviceVulkan13Properties',['../struct_vk_physical_device_vulkan13_properties.html',1,'']]],
  ['vkphysicaldevicevulkanmemorymodelfeatures_348',['VkPhysicalDeviceVulkanMemoryModelFeatures',['../struct_vk_physical_device_vulkan_memory_model_features.html',1,'']]],
  ['vkphysicaldevicezeroinitializeworkgroupmemoryfeatures_349',['VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures',['../struct_vk_physical_device_zero_initialize_workgroup_memory_features.html',1,'']]],
  ['vkpipelinecachecreateinfo_350',['VkPipelineCacheCreateInfo',['../struct_vk_pipeline_cache_create_info.html',1,'']]],
  ['vkpipelinecacheheaderversionone_351',['VkPipelineCacheHeaderVersionOne',['../struct_vk_pipeline_cache_header_version_one.html',1,'']]],
  ['vkpipelinecolorblendattachmentstate_352',['VkPipelineColorBlendAttachmentState',['../struct_vk_pipeline_color_blend_attachment_state.html',1,'']]],
  ['vkpipelinecolorblendstatecreateinfo_353',['VkPipelineColorBlendStateCreateInfo',['../struct_vk_pipeline_color_blend_state_create_info.html',1,'']]],
  ['vkpipelinecreationfeedback_354',['VkPipelineCreationFeedback',['../struct_vk_pipeline_creation_feedback.html',1,'']]],
  ['vkpipelinecreationfeedbackcreateinfo_355',['VkPipelineCreationFeedbackCreateInfo',['../struct_vk_pipeline_creation_feedback_create_info.html',1,'']]],
  ['vkpipelinedepthstencilstatecreateinfo_356',['VkPipelineDepthStencilStateCreateInfo',['../struct_vk_pipeline_depth_stencil_state_create_info.html',1,'']]],
  ['vkpipelinedynamicstatecreateinfo_357',['VkPipelineDynamicStateCreateInfo',['../struct_vk_pipeline_dynamic_state_create_info.html',1,'']]],
  ['vkpipelineinputassemblystatecreateinfo_358',['VkPipelineInputAssemblyStateCreateInfo',['../struct_vk_pipeline_input_assembly_state_create_info.html',1,'']]],
  ['vkpipelinelayoutcreateinfo_359',['VkPipelineLayoutCreateInfo',['../struct_vk_pipeline_layout_create_info.html',1,'']]],
  ['vkpipelinemultisamplestatecreateinfo_360',['VkPipelineMultisampleStateCreateInfo',['../struct_vk_pipeline_multisample_state_create_info.html',1,'']]],
  ['vkpipelinerasterizationstatecreateinfo_361',['VkPipelineRasterizationStateCreateInfo',['../struct_vk_pipeline_rasterization_state_create_info.html',1,'']]],
  ['vkpipelinerenderingcreateinfo_362',['VkPipelineRenderingCreateInfo',['../struct_vk_pipeline_rendering_create_info.html',1,'']]],
  ['vkpipelineshaderstagecreateinfo_363',['VkPipelineShaderStageCreateInfo',['../struct_vk_pipeline_shader_stage_create_info.html',1,'']]],
  ['vkpipelineshaderstagerequiredsubgroupsizecreateinfo_364',['VkPipelineShaderStageRequiredSubgroupSizeCreateInfo',['../struct_vk_pipeline_shader_stage_required_subgroup_size_create_info.html',1,'']]],
  ['vkpipelinetessellationdomainoriginstatecreateinfo_365',['VkPipelineTessellationDomainOriginStateCreateInfo',['../struct_vk_pipeline_tessellation_domain_origin_state_create_info.html',1,'']]],
  ['vkpipelinetessellationstatecreateinfo_366',['VkPipelineTessellationStateCreateInfo',['../struct_vk_pipeline_tessellation_state_create_info.html',1,'']]],
  ['vkpipelinevertexinputstatecreateinfo_367',['VkPipelineVertexInputStateCreateInfo',['../struct_vk_pipeline_vertex_input_state_create_info.html',1,'']]],
  ['vkpipelineviewportstatecreateinfo_368',['VkPipelineViewportStateCreateInfo',['../struct_vk_pipeline_viewport_state_create_info.html',1,'']]],
  ['vkpresentinfokhr_369',['VkPresentInfoKHR',['../struct_vk_present_info_k_h_r.html',1,'']]],
  ['vkprivatedataslotcreateinfo_370',['VkPrivateDataSlotCreateInfo',['../struct_vk_private_data_slot_create_info.html',1,'']]],
  ['vkprotectedsubmitinfo_371',['VkProtectedSubmitInfo',['../struct_vk_protected_submit_info.html',1,'']]],
  ['vkpushconstantrange_372',['VkPushConstantRange',['../struct_vk_push_constant_range.html',1,'']]],
  ['vkquerypoolcreateinfo_373',['VkQueryPoolCreateInfo',['../struct_vk_query_pool_create_info.html',1,'']]],
  ['vkqueuefamilyproperties_374',['VkQueueFamilyProperties',['../struct_vk_queue_family_properties.html',1,'']]],
  ['vkqueuefamilyproperties2_375',['VkQueueFamilyProperties2',['../struct_vk_queue_family_properties2.html',1,'']]],
  ['vkrect2d_376',['VkRect2D',['../struct_vk_rect2_d.html',1,'']]],
  ['vkrenderingattachmentinfo_377',['VkRenderingAttachmentInfo',['../struct_vk_rendering_attachment_info.html',1,'']]],
  ['vkrenderinginfo_378',['VkRenderingInfo',['../struct_vk_rendering_info.html',1,'']]],
  ['vkrenderpassattachmentbegininfo_379',['VkRenderPassAttachmentBeginInfo',['../struct_vk_render_pass_attachment_begin_info.html',1,'']]],
  ['vkrenderpassbegininfo_380',['VkRenderPassBeginInfo',['../struct_vk_render_pass_begin_info.html',1,'']]],
  ['vkrenderpasscreateinfo_381',['VkRenderPassCreateInfo',['../struct_vk_render_pass_create_info.html',1,'']]],
  ['vkrenderpasscreateinfo2_382',['VkRenderPassCreateInfo2',['../struct_vk_render_pass_create_info2.html',1,'']]],
  ['vkrenderpassinputattachmentaspectcreateinfo_383',['VkRenderPassInputAttachmentAspectCreateInfo',['../struct_vk_render_pass_input_attachment_aspect_create_info.html',1,'']]],
  ['vkrenderpassmultiviewcreateinfo_384',['VkRenderPassMultiviewCreateInfo',['../struct_vk_render_pass_multiview_create_info.html',1,'']]],
  ['vkresolveimageinfo2_385',['VkResolveImageInfo2',['../struct_vk_resolve_image_info2.html',1,'']]],
  ['vksamplercreateinfo_386',['VkSamplerCreateInfo',['../struct_vk_sampler_create_info.html',1,'']]],
  ['vksamplerreductionmodecreateinfo_387',['VkSamplerReductionModeCreateInfo',['../struct_vk_sampler_reduction_mode_create_info.html',1,'']]],
  ['vksamplerycbcrconversioncreateinfo_388',['VkSamplerYcbcrConversionCreateInfo',['../struct_vk_sampler_ycbcr_conversion_create_info.html',1,'']]],
  ['vksamplerycbcrconversionimageformatproperties_389',['VkSamplerYcbcrConversionImageFormatProperties',['../struct_vk_sampler_ycbcr_conversion_image_format_properties.html',1,'']]],
  ['vksamplerycbcrconversioninfo_390',['VkSamplerYcbcrConversionInfo',['../struct_vk_sampler_ycbcr_conversion_info.html',1,'']]],
  ['vksemaphorecreateinfo_391',['VkSemaphoreCreateInfo',['../struct_vk_semaphore_create_info.html',1,'']]],
  ['vksemaphoresignalinfo_392',['VkSemaphoreSignalInfo',['../struct_vk_semaphore_signal_info.html',1,'']]],
  ['vksemaphoresubmitinfo_393',['VkSemaphoreSubmitInfo',['../struct_vk_semaphore_submit_info.html',1,'']]],
  ['vksemaphoretypecreateinfo_394',['VkSemaphoreTypeCreateInfo',['../struct_vk_semaphore_type_create_info.html',1,'']]],
  ['vksemaphorewaitinfo_395',['VkSemaphoreWaitInfo',['../struct_vk_semaphore_wait_info.html',1,'']]],
  ['vkshadermodulecreateinfo_396',['VkShaderModuleCreateInfo',['../struct_vk_shader_module_create_info.html',1,'']]],
  ['vksparsebuffermemorybindinfo_397',['VkSparseBufferMemoryBindInfo',['../struct_vk_sparse_buffer_memory_bind_info.html',1,'']]],
  ['vksparseimageformatproperties_398',['VkSparseImageFormatProperties',['../struct_vk_sparse_image_format_properties.html',1,'']]],
  ['vksparseimageformatproperties2_399',['VkSparseImageFormatProperties2',['../struct_vk_sparse_image_format_properties2.html',1,'']]],
  ['vksparseimagememorybind_400',['VkSparseImageMemoryBind',['../struct_vk_sparse_image_memory_bind.html',1,'']]],
  ['vksparseimagememorybindinfo_401',['VkSparseImageMemoryBindInfo',['../struct_vk_sparse_image_memory_bind_info.html',1,'']]],
  ['vksparseimagememoryrequirements_402',['VkSparseImageMemoryRequirements',['../struct_vk_sparse_image_memory_requirements.html',1,'']]],
  ['vksparseimagememoryrequirements2_403',['VkSparseImageMemoryRequirements2',['../struct_vk_sparse_image_memory_requirements2.html',1,'']]],
  ['vksparseimageopaquememorybindinfo_404',['VkSparseImageOpaqueMemoryBindInfo',['../struct_vk_sparse_image_opaque_memory_bind_info.html',1,'']]],
  ['vksparsememorybind_405',['VkSparseMemoryBind',['../struct_vk_sparse_memory_bind.html',1,'']]],
  ['vkspecializationinfo_406',['VkSpecializationInfo',['../struct_vk_specialization_info.html',1,'']]],
  ['vkspecializationmapentry_407',['VkSpecializationMapEntry',['../struct_vk_specialization_map_entry.html',1,'']]],
  ['vkstencilopstate_408',['VkStencilOpState',['../struct_vk_stencil_op_state.html',1,'']]],
  ['vksubmitinfo_409',['VkSubmitInfo',['../struct_vk_submit_info.html',1,'']]],
  ['vksubmitinfo2_410',['VkSubmitInfo2',['../struct_vk_submit_info2.html',1,'']]],
  ['vksubpassbegininfo_411',['VkSubpassBeginInfo',['../struct_vk_subpass_begin_info.html',1,'']]],
  ['vksubpassdependency_412',['VkSubpassDependency',['../struct_vk_subpass_dependency.html',1,'']]],
  ['vksubpassdependency2_413',['VkSubpassDependency2',['../struct_vk_subpass_dependency2.html',1,'']]],
  ['vksubpassdescription_414',['VkSubpassDescription',['../struct_vk_subpass_description.html',1,'']]],
  ['vksubpassdescription2_415',['VkSubpassDescription2',['../struct_vk_subpass_description2.html',1,'']]],
  ['vksubpassdescriptiondepthstencilresolve_416',['VkSubpassDescriptionDepthStencilResolve',['../struct_vk_subpass_description_depth_stencil_resolve.html',1,'']]],
  ['vksubpassendinfo_417',['VkSubpassEndInfo',['../struct_vk_subpass_end_info.html',1,'']]],
  ['vksubresourcelayout_418',['VkSubresourceLayout',['../struct_vk_subresource_layout.html',1,'']]],
  ['vksurfacecapabilitieskhr_419',['VkSurfaceCapabilitiesKHR',['../struct_vk_surface_capabilities_k_h_r.html',1,'']]],
  ['vksurfaceformatkhr_420',['VkSurfaceFormatKHR',['../struct_vk_surface_format_k_h_r.html',1,'']]],
  ['vkswapchaincreateinfokhr_421',['VkSwapchainCreateInfoKHR',['../struct_vk_swapchain_create_info_k_h_r.html',1,'']]],
  ['vktimelinesemaphoresubmitinfo_422',['VkTimelineSemaphoreSubmitInfo',['../struct_vk_timeline_semaphore_submit_info.html',1,'']]],
  ['vkvertexinputattributedescription_423',['VkVertexInputAttributeDescription',['../struct_vk_vertex_input_attribute_description.html',1,'']]],
  ['vkvertexinputbindingdescription_424',['VkVertexInputBindingDescription',['../struct_vk_vertex_input_binding_description.html',1,'']]],
  ['vkviewport_425',['VkViewport',['../struct_vk_viewport.html',1,'']]],
  ['vkwaylandsurfacecreateinfokhr_426',['VkWaylandSurfaceCreateInfoKHR',['../struct_vk_wayland_surface_create_info_k_h_r.html',1,'']]],
  ['vkwin32surfacecreateinfokhr_427',['VkWin32SurfaceCreateInfoKHR',['../struct_vk_win32_surface_create_info_k_h_r.html',1,'']]],
  ['vkwritedescriptorset_428',['VkWriteDescriptorSet',['../struct_vk_write_descriptor_set.html',1,'']]],
  ['vkwritedescriptorsetinlineuniformblock_429',['VkWriteDescriptorSetInlineUniformBlock',['../struct_vk_write_descriptor_set_inline_uniform_block.html',1,'']]],
  ['vkxcbsurfacecreateinfokhr_430',['VkXcbSurfaceCreateInfoKHR',['../struct_vk_xcb_surface_create_info_k_h_r.html',1,'']]],
  ['vkxlibsurfacecreateinfokhr_431',['VkXlibSurfaceCreateInfoKHR',['../struct_vk_xlib_surface_create_info_k_h_r.html',1,'']]],
  ['vml_5fassign_5ftraits_432',['vml_assign_traits',['../class_eigen_1_1internal_1_1vml__assign__traits.html',1,'Eigen::internal']]],
  ['voicestate_433',['VoiceState',['../class_voice_state.html',1,'']]],
  ['void_5fcaster_434',['void_caster',['../structvoid__caster.html',1,'']]],
  ['void_5fcaster_3c_20std_3a_3anullptr_5ft_20_3e_435',['void_caster&lt; std::nullptr_t &gt;',['../structvoid__caster.html',1,'']]],
  ['void_5fcaster_3c_20void_5ftype_20_3e_436',['void_caster&lt; void_type &gt;',['../structvoid__caster.html',1,'']]],
  ['void_5ft_5fimpl_437',['void_t_impl',['../structvoid__t__impl.html',1,'']]],
  ['void_5ftype_438',['void_type',['../structvoid__type.html',1,'']]],
  ['volume_439',['volume',['../class_eigen_1_1_aligned_box.html#af737027346c35a1c3027d36c9c891dc5',1,'Eigen::AlignedBox']]],
  ['vresize_440',['VResize',['../nanogui_2include_2nanogui_2common_8h.html#ac9c915d433bdce7b6b47c0956c850f43a93a638f3f74a90ce3d236ea57e36e6b9',1,'common.h']]],
  ['vs_20dynamic_20size_441',['Fixed vs. Dynamic size',['..//Users/ferluht/Dev/rpidaw/3rdparty/nanogui/ext/eigen/doc/TutorialMatrixClass.dox#TutorialMatrixFixedVsDynamic',1,'']]],
  ['vs_20extrinsic_20euler_20systems_442',['Intrinsic vs extrinsic Euler systems',['../class_eigen_1_1_euler_system.html#autotoc_md231',1,'']]],
  ['vscrollpanel_443',['VScrollPanel',['../class_v_scroll_panel.html',1,'']]],
  ['vscrollpanel_2eh_444',['vscrollpanel.h',['../vscrollpanel_8h.html',1,'']]],
  ['vulkan_445',['Support for Vulkan',['../news.html#news_32_vulkan',1,'']]],
  ['vulkan_20extensions_446',['Querying required Vulkan extensions',['../vulkan_guide.html#vulkan_ext',1,'']]],
  ['vulkan_20function_20pointers_447',['Querying Vulkan function pointers',['../vulkan_guide.html#vulkan_proc',1,'']]],
  ['vulkan_20guide_448',['Vulkan guide',['../vulkan_guide.html',1,'']]],
  ['vulkan_20header_20file_449',['Including the Vulkan header file',['../vulkan_guide.html#vulkan_include',1,'']]],
  ['vulkan_20loader_450',['Finding the Vulkan loader',['../vulkan_guide.html#vulkan_loader',1,'']]],
  ['vulkan_20loader_20and_20api_451',['Vulkan loader and API',['../compat_guide.html#compat_vulkan',1,'']]],
  ['vulkan_20presentation_20support_452',['Querying for Vulkan presentation support',['../vulkan_guide.html#vulkan_present',1,'']]],
  ['vulkan_20support_453',['Querying for Vulkan support',['../vulkan_guide.html#vulkan_support',1,'']]],
  ['vulkan_20support_20reference_454',['Vulkan support reference',['../group__vulkan.html',1,'']]],
  ['vulkan_20window_20surface_455',['Creating a Vulkan window surface',['../vulkan_guide.html#vulkan_surface',1,'']]],
  ['vulkan_20wsi_20extensions_456',['Vulkan WSI extensions',['../compat_guide.html#compat_wsi',1,'']]]
];
