var annotated_dup =
[
    [ "A", "class_a.html", "class_a" ],
    [ "AMG", "class_a_m_g.html", null ],
    [ "AudioEffect", "class_audio_effect.html", null ],
    [ "DAW", "class_d_a_w.html", "class_d_a_w" ],
    [ "DummyAudioFX", "class_dummy_audio_f_x.html", "class_dummy_audio_f_x" ],
    [ "DummyInstrument", "class_dummy_instrument.html", "class_dummy_instrument" ],
    [ "DummyMidiFX", "class_dummy_midi_f_x.html", "class_dummy_midi_f_x" ],
    [ "Effect", "class_effect.html", null ],
    [ "G", "class_g.html", "class_g" ],
    [ "Instrument", "class_instrument.html", null ],
    [ "M", "class_m.html", "class_m" ],
    [ "MData", "struct_m_data.html", null ],
    [ "MIDIEffect", "class_m_i_d_i_effect.html", null ],
    [ "MIDIMap", "class_m_i_d_i_map.html", "class_m_i_d_i_map" ],
    [ "Plateau", "class_plateau.html", "class_plateau" ],
    [ "PolyInstrument", "class_poly_instrument.html", "class_poly_instrument" ],
    [ "Rack", "class_rack.html", "class_rack" ],
    [ "SampleKit", "class_sample_kit.html", "class_sample_kit" ],
    [ "Sampler", "class_sampler.html", "class_sampler" ],
    [ "SamplerState", "class_sampler_state.html", null ],
    [ "Scale", "class_scale.html", "class_scale" ],
    [ "SimpleInstrument", "class_simple_instrument.html", "class_simple_instrument" ],
    [ "SimpleInstrumentVoiceState", "class_simple_instrument_voice_state.html", null ],
    [ "SingleTone", "class_single_tone.html", "class_single_tone" ],
    [ "SingleToneVoiceState", "class_single_tone_voice_state.html", null ],
    [ "Tape", "class_tape.html", "class_tape" ],
    [ "TapeRack", "class_tape_rack.html", "class_tape_rack" ],
    [ "VoiceState", "class_voice_state.html", null ]
];